crates/exex/src/model.rs

model: implement `KethU256`

---

crates/exex/src/model.rs

model: impl `From<Bloom>` for `KethMaybeRelocatables`

---

Cargo.lock
Cargo.toml
crates/exex/Cargo.toml
crates/exex/src/model.rs

model: impl `From<Transaction>` for `KethPointer`

---

Cargo.lock
crates/exex/Cargo.toml
crates/exex/src/serde.rs

To have https://github.com/lambdaclass/cairo-vm/pull/1861

bump cairo-vm to 6025257

---

crates/exex/src/hints.rs

Should close https://github.com/kkrt-labs/keth/issues/108

rust hints: add block hint scaffolding

---

cairo/src/precompiles/precompiles.cairo
cairo/tests/utils/hints.py

Just some unused and so misleading python hints

Remove unused hints

---

.vscode/settings.json
cairo/ethereum/cancun/fork_types.cairo
cairo/src/utils/bytes.cairo
cairo/tests/src/utils/test_bytes.py

fix: enforce code_hash is 32 bytes long

---

cairo/src/precompiles/ripemd160.cairo
cairo/tests/src/precompiles/test_ripemd160.py
cairo/tests/utils/errors.py
cairo/tests/utils/hints.py

Closes #147
Finalize dict and set the pointer start to the correct value

fix: finalize dictionary in RIPEMD160

---

crates/exex/src/model/event.rs

Should close https://github.com/kkrt-labs/keth/issues/202

impl `From<LogData>` for `KethEvent`

---

cairo/src/interpreter.cairo
cairo/tests/programs/test_os.py
cairo/tests/utils/helpers.py

Closes #143
Return the contract code for create txs

fix: returndata of create txs

---

crates/exex/src/model/account.rs
crates/exex/src/model/mod.rs
crates/exex/src/model/primitives.rs

Should close https://github.com/kkrt-labs/keth/issues/208

add `Account` model

---

.github/workflows/nighly_fuzzing.yml
cairo/tests/conftest.py

ci: add nightly fuzzing job

---

cairo/src/state.cairo
cairo/tests/src/test_state.cairo
cairo/tests/src/test_state.py

fix: adds carry check add transfer

---

cairo/src/gas.cairo
cairo/tests/src/test_gas.py

fix: high offset memory expansion computations

---

.github/workflows/python_tests.yml

ci: run test with src if modified

---

cairo/src/utils/utils.cairo
cairo/tests/src/utils/test_utils.cairo
cairo/tests/src/utils/test_utils.py
cairo/tests/utils/helpers.py

Close #259
See https://github.com/kkrt-labs/keth/issues/259#issuecomment-2539149408
(seems to fix the hypothesis/.tmp problem also)

dev: remove unused utils functions

---

.github/workflows/nighly_fuzzing.yml
.github/workflows/python_tests.yml

ci:  separate forge steps

---

.github/workflows/cleanup_cache.yml

ci: delete cache on PR merge

---

cairo/ethereum_types/numeric.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py

feat: implement Set[Uint] type

---

cairo/src/utils/compile_cairo.py
cairo/src/utils/compiler.py
cairo/src/utils/constants.py
cairo/tests/fixtures/compiler.py
cairo/tests/utils/hints.py

feat: use the same compiler in cairo_compile and in tests

---

cairo/tests/fixtures/runner.py
cairo/tests/utils/serde.py

Closes #255
Closes #256
trust me, it works

feat: handle implicit args in runner

---

cairo/ethereum/cancun/utils/address.cairo
cairo/tests/ethereum/cancun/utils/test_address.py

feat: compute contract address

---

cairo/ethereum/exceptions.cairo
cairo/tests/test_serde.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py

feat: error types

---

cairo/ethereum/cancun/trie.cairo
cairo/ethereum_types/bytes.cairo
cairo/ethereum_types/others.cairo
cairo/tests/fixtures/compiler.py
cairo/tests/fixtures/runner.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/compiler.py
cairo/tests/utils/serde.py

Summarized our meeting notes in the form of in-code documentation.

docs: add code doc for test and type system

---

cairo/ethereum/cancun/vm/runtime.cairo
cairo/tests/ethereum/cancun/vm/test_runtime.py

feat: get_valid_jump_destinations

---

.github/workflows/trunk_check.yml
.trunk/trunk.yaml
cairo/ethereum/cancun/fork_types.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py

resolves #293 
implement SetAddress as `EVM` object has `address_to_delete` field that is a set of addresses

dev: add SetAddress cairo type to prepare for EVM object

---

cairo/ethereum/cancun/utils/address.cairo
cairo/ethereum_types/numeric.cairo
cairo/tests/ethereum/cancun/utils/test_address.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py

feat: implement to_address

---

cairo/ethereum/cancun/fork_types.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py

participates to https://github.com/kkrt-labs/keth/issues/30
resolves https://github.com/kkrt-labs/keth/issues/297

dev: add Set[Tuple[Address, Bytes32]] and Tuple[Address, Bytes32] 

---

cairo/ethereum/cancun/vm/exceptions.cairo
cairo/ethereum/cancun/vm/stack.cairo
cairo/pyproject.toml
cairo/tests/ethereum/cancun/vm/test_stack.py
cairo/tests/fixtures/runner.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
uv.lock

Cairo repro of the EELS stack, including proper arg generation / serde with python
Closes #258
Closes #254
Needs to merge #310 before

feat: EELS stack

---

cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py

use explicit Stack type for mutable data structure

---

cairo/ethereum/cancun/state.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py

feat: state struct

---

cairo/ethereum/cancun/fork_types.cairo
cairo/ethereum/cancun/vm.cairo
cairo/tests/test_serde.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py

closes https://github.com/kkrt-labs/keth/issues/302

feat: environment struct

---

cairo/tests/conftest.py
cairo/tests/fixtures/runner.py
cairo/tests/utils/compiler.py

Start loading compiled programs as soon as compilation is done

---

.github/workflows/nightly_fuzzing.yml

Also fix typo in filename
Part of #318

fix: nightly python-version-file path

---

.github/workflows/python_tests.yml

ci: fix cache path

---

cairo/ethereum/cancun/vm/instructions/block.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_block.py
cairo/tests/utils/strategies.py

feat: block operations opcodes

---

cairo/ethereum/cancun/vm.cairo
cairo/ethereum/cancun/vm/instructions/log.cairo
cairo/ethereum/utils/numeric.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_keccak.py
cairo/tests/ethereum/cancun/vm/instructions/test_log.py
cairo/tests/ethereum/cancun/vm/test_memory.py
cairo/tests/ethereum/utils/test_numeric.py
cairo/tests/utils/strategies.py

feat: logs

---

.github/workflows/cleanup_cache.yml

ci: improve logging cleanup cache

---

cairo/ethereum/cancun/vm/instructions/stack_instructions.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_stack_instructions.py

feat: dup_n

---

cairo/tests/ethereum/cancun/vm/instructions/test_arithmetic.py
cairo/tests/ethereum/cancun/vm/instructions/test_bitwise.py
cairo/tests/ethereum/cancun/vm/instructions/test_block.py
cairo/tests/utils/evm_builder.py
cairo/tests/utils/strategies.py

Close #384 
Profiling: `uv run pytest -k test_and --profile`
Before
After

test: evm builder

---

cairo/ethereum/cancun/fork_types.cairo
cairo/ethereum/cancun/state.cairo
cairo/ethereum/cancun/trie.cairo
cairo/ethereum_types/bytes.cairo
cairo/tests/ethereum/cancun/test_trie.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py

Closes https://github.com/kkrt-labs/keth/issues/361

feat: trie copy

---

cairo/ethereum/cancun/state.cairo
cairo/src/utils/dict.cairo
cairo/tests/ethereum/cancun/test_state.py
cairo/tests/utils/strategies.py

feat: add `get_account` and `get_account_optional` and `get_storage` to `state.cairo`
closes #388 
closes #391

feat: add `get_account` and `get_account_optional` and `get_storage` to `state.cairo`

---

cairo/ethereum/cancun/state.cairo
cairo/tests/ethereum/cancun/test_state.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py

feat: set_transient_storage

---

cairo/ethereum/cancun/state.cairo
cairo/tests/ethereum/cancun/test_state.py

feat: account_has_code_or_nonce

---

cairo/ethereum/cancun/state.cairo
cairo/tests/ethereum/cancun/test_state.py

feat: is_account_empty

---

cairo/ethereum/cancun/state.cairo
cairo/tests/ethereum/cancun/test_state.py

feat: mark_account_created

---

cairo/ethereum/cancun/state.cairo
cairo/tests/ethereum/cancun/test_state.py

destroy storage
destroy account
closes #406

feat: destroy_storage, destroy_account

---

cairo/ethereum/cancun/state.cairo
cairo/tests/ethereum/cancun/test_state.py

feat: account_exists_and_is_empty

---

cairo/ethereum/cancun/state.cairo
cairo/tests/ethereum/cancun/test_state.py

feat: begin transaction

---

cairo/ethereum/cancun/state.cairo
cairo/tests/ethereum/cancun/test_state.py

feat: set_code

---

cairo/ethereum/cancun/state.cairo
cairo/tests/ethereum/cancun/test_state.py

feat: set account balance

---

cairo/tests/utils/strategies.py

test: account strategy and limit trie data size

---

cairo/ethereum/cancun/state.cairo

fix: get_storage_original

---

cairo/ethereum/cancun/vm/instructions/environment.cairo
cairo/src/gas.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_environment.py
cairo/tests/utils/evm_builder.py
cairo/tests/utils/strategies.py

feat: codecopy

---

cairo/ethereum/cancun/state.cairo
cairo/tests/ethereum/cancun/test_state.py

feat: destroy_touched_empty_accounts

---

cairo/ethereum/cancun/fork_types.cairo
cairo/ethereum/cancun/state.cairo
cairo/ethereum/cancun/trie.cairo
cairo/src/utils/dict.cairo
cairo/tests/conftest.py
cairo/tests/ethereum/cancun/test_state.py
cairo/tests/ethereum/cancun/test_trie.py
cairo/tests/src/utils/test_dict.cairo
cairo/tests/src/utils/test_dict.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py
crates/cairo-addons/src/vm/hint_definitions/hashdict.rs
python/cairo-addons/src/cairo_addons/hints/hashdict.py

Closes https://github.com/kkrt-labs/keth/issues/503

feat: flatten storage tries with hashes

---

cairo/ethereum/cancun/vm/exceptions.cairo
cairo/ethereum/cancun/vm/gas.cairo
cairo/ethereum/cancun/vm/instructions/arithmetic.cairo
cairo/ethereum/cancun/vm/instructions/bitwise.cairo
cairo/ethereum/cancun/vm/instructions/block.cairo
cairo/ethereum/cancun/vm/instructions/comparison.cairo
cairo/ethereum/cancun/vm/instructions/control_flow.cairo
cairo/ethereum/cancun/vm/instructions/environment.cairo
cairo/ethereum/cancun/vm/instructions/keccak.cairo
cairo/ethereum/cancun/vm/instructions/log.cairo
cairo/ethereum/cancun/vm/instructions/memory_instructions.cairo
cairo/ethereum/cancun/vm/instructions/stack_instructions.cairo
cairo/ethereum/cancun/vm/instructions/storage.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/ethereum/cancun/vm/stack.cairo
cairo/ethereum/exceptions.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_bitwise.py
cairo/tests/ethereum/cancun/vm/instructions/test_block.py
cairo/tests/ethereum/cancun/vm/instructions/test_comparison.py
cairo/tests/ethereum/cancun/vm/instructions/test_control_flow.py
cairo/tests/ethereum/cancun/vm/instructions/test_environment.py
cairo/tests/ethereum/cancun/vm/instructions/test_keccak.py
cairo/tests/ethereum/cancun/vm/instructions/test_log.py
cairo/tests/ethereum/cancun/vm/instructions/test_memory_instructions.py
cairo/tests/ethereum/cancun/vm/instructions/test_stack_instructions.py
cairo/tests/ethereum/cancun/vm/instructions/test_system.py
cairo/tests/ethereum/cancun/vm/test_gas.py
cairo/tests/test_serde.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py

Closes #469 
Side effect: change how errors are handled as `Revert` is an `EthereumException`

feat: revert opcode

---

cairo/ethereum/cancun/vm.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_system.py

feat: return_ opcode

---

cairo/ethereum/cancun/vm/exceptions.cairo
cairo/ethereum/cancun/vm/instructions.cairo
cairo/ethereum/cancun/vm/instructions/arithmetic.cairo
cairo/ethereum/cancun/vm/instructions/bitwise.cairo
cairo/ethereum/cancun/vm/instructions/block.cairo
cairo/ethereum/cancun/vm/instructions/comparison.cairo
cairo/ethereum/cancun/vm/instructions/control_flow.cairo
cairo/ethereum/cancun/vm/instructions/environment.cairo
cairo/ethereum/cancun/vm/instructions/keccak.cairo
cairo/ethereum/cancun/vm/instructions/log.cairo
cairo/ethereum/cancun/vm/instructions/memory_instructions.cairo
cairo/ethereum/cancun/vm/instructions/stack_instructions.cairo
cairo/ethereum/cancun/vm/instructions/storage.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/tests/ethereum/cancun/vm/test_instructions.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py

feat: op_implementation

---

cairo/ethereum/cancun/trie.cairo
cairo/ethereum/cancun/vm/instructions.cairo
cairo/ethereum/cancun/vm/interpreter.cairo
cairo/ethereum/cancun/vm/memory.cairo
cairo/tests/ethereum/cancun/vm/test_interpreter.py
cairo/tests/utils/args_gen.py

Closes #519
https://github.com/ethereum/execution-specs/blob/e4d7b402a7bda2812e1723642b99614fcdd55193/src/ethereum/cancun/vm/interpreter.py#L248

feat: execute_code

---

cairo/ethereum/cancun/vm/interpreter.cairo
cairo/src/utils/dict.cairo
cairo/tests/ethereum/cancun/vm/test_interpreter.py
crates/cairo-addons/src/vm/hint_definitions/dict.rs
python/cairo-addons/src/cairo_addons/hints/dict.py

feat: process_message

---

Cargo.lock
Cargo.toml
crates/cairo-addons/src/vm/hint_definitions/dict.rs
python/cairo-addons/src/cairo_addons/hints/dict.py

issue was: copy_dict_segment would copy the dict's data but not its default value.

fix copy dict hint to support default value

---

cairo/tests/fixtures/runner.py
crates/cairo-addons/src/vm/runner.rs

dev: enable arbitrary builtin order for rust vm

---

cairo/ethereum/cancun/utils/constants.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/ethereum/cancun/vm/interpreter.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_system_cairo.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_system_cairo.py

WIP:
- implement generic call
- implement test
- squash all dicts when returning

add generic call 

---

cairo/ethereum/cancun/vm/instructions.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_system_cairo.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_system_cairo.py

feat: create opcodes

---

cairo/ethereum/cancun/trie.cairo
cairo/ethereum_rlp/rlp.cairo
cairo/tests/ethereum_rlp/test_rlp.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/strategies.py
pyproject.toml
uv.lock

dev: update eels

---

cairo/ethereum/cancun/state.cairo
cairo/ethereum/cancun/vm/interpreter.cairo
cairo/tests/ethereum/cancun/test_state.py
cairo/tests/ethereum/cancun/vm/test_interpreter.py
cairo/tests/test_serde.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py

Closes #528 
See [53fbc954b8e9e7dd86060814dfbf836791a22f4c](https://github.com/kkrt-labs/execution-specs/commit/53fbc954b8e9e7dd86060814dfbf836791a22f4c) for change of EELS

feat: process_message_call

---

cairo/ethereum/cancun/vm/instructions/system.cairo

bug: add account_has_storage check in generic_create

---

cairo/tests/utils/evm_builder.py
cairo/tests/utils/message_builder.py
cairo/tests/utils/strategies.py

fix: mutable object strategy generation (2)

---

cairo/ethereum/cancun/vm/instructions.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/ethereum/utils/numeric.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_system_cairo.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_system_cairo.py

closes #551 
closes #552 
closes #550

feat: add other call opcodes

---

cairo/ethereum_rlp/rlp.cairo
cairo/tests/ethereum_rlp/test_rlp.py

feat: encode transactions

---

Cargo.lock
cairo/ethereum/cancun/fork_types.cairo
cairo/ethereum/cancun/utils/message.cairo
cairo/ethereum/cancun/vm.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/tests/ethereum/cancun/utils/test_message.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
crates/cairo-addons/Cargo.toml
crates/cairo-addons/src/vm/hint_definitions/hashdict.rs
python/cairo-addons/src/cairo_addons/hints/hashdict.py

feat: prepare_message

---

cairo/ethereum/cancun/fork.cairo
cairo/ethereum/cancun/vm.cairo
cairo/ethereum/cancun/vm/interpreter.cairo
cairo/ethereum/exceptions.cairo
cairo/ethereum_rlp/rlp.cairo
cairo/tests/ethereum/cancun/test_fork.py
cairo/tests/utils/args_gen.py
uv.lock

feat: make_receipt

---

cairo/ethereum/cancun/vm/instructions.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_system.py
cairo/tests/ethereum/cancun/vm/test_instructions.py
cairo/tests/utils/serde.py

feat: selfdestruct

---

cairo/ethereum/cancun/vm/precompiled_contracts/identity.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/mapping.cairo
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_identity.py
cairo/tests/ethereum/cancun/vm/test_interpreter.py

feat: identity precompile

---

cairo/ethereum/cancun/fork.cairo
cairo/ethereum/utils/numeric.cairo

fix overflow in check transaction

---

cairo/ethereum/cancun/blocks.cairo
cairo/ethereum/cancun/trie.cairo
cairo/tests/ethereum/cancun/test_trie.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py
crates/cairo-addons/src/vm/hint_definitions/hashdict.rs
python/cairo-addons/src/cairo_addons/hints/hashdict.py
uv.lock

feat: transaction trie

---

cairo/ethereum/cancun/blocks.cairo
cairo/ethereum/cancun/trie.cairo
cairo/tests/ethereum/cancun/test_trie.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py

Closes #635 
Needs #634 to be merged before

feat: receipts trie

---

cairo/tests/ethereum/cancun/vm/test_runtime.py

dev: improve test cases

---

cairo/tests/conftest.py
cairo/tests/ethereum/cancun/test_vm.py
cairo/tests/ethereum/cancun/vm/instructions/test_arithmetic.py
cairo/tests/ethereum/cancun/vm/instructions/test_bitwise.py
cairo/tests/ethereum/cancun/vm/instructions/test_block.py
cairo/tests/ethereum/cancun/vm/instructions/test_comparison.py
cairo/tests/ethereum/cancun/vm/instructions/test_control_flow.py
cairo/tests/ethereum/cancun/vm/instructions/test_environment.py
cairo/tests/ethereum/cancun/vm/instructions/test_keccak.py
cairo/tests/ethereum/cancun/vm/instructions/test_log.py
cairo/tests/ethereum/cancun/vm/instructions/test_memory_instructions.py
cairo/tests/ethereum/cancun/vm/instructions/test_stack_instructions.py
cairo/tests/ethereum/cancun/vm/instructions/test_storage.py
cairo/tests/ethereum/cancun/vm/instructions/test_system.py
cairo/tests/ethereum/cancun/vm/instructions/test_system_cairo.py
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_identity.py
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_sha256.py
cairo/tests/ethereum/cancun/vm/test_gas.py
cairo/tests/ethereum/cancun/vm/test_instructions.py
cairo/tests/test_patches.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/evm_builder.py
cairo/tests/utils/message_builder.py
cairo/tests/utils/strategies.py

dev: auto-patch all modified ethereum imports

---

cairo/ethereum/cancun/bloom.cairo
cairo/ethereum/cancun/state.cairo
cairo/ethereum/cancun/vm/instructions/control_flow.cairo
cairo/ethereum/cancun/vm/instructions/stack_instructions.cairo
cairo/ethereum/cancun/vm/memory.cairo
cairo/ethereum/cancun/vm/runtime.cairo
cairo/ethereum/cancun/vm/stack.cairo
cairo/src/utils/dict.cairo
cairo/tests/utils/args_gen.py
crates/cairo-addons/src/vm/hint_definitions/hashdict.rs
python/cairo-addons/src/cairo_addons/hints/hashdict.py

dev: refactor dict_{read/write} for coherency

---

.github/workflows/nightly_fuzzing.yml
.github/workflows/python_tests.yml
.gitignore
.vscode/settings.json
cairo/tests/conftest.py
codecov.yml
python/cairo-addons/src/cairo_addons/profiler.py
python/cairo-addons/src/cairo_addons/testing/coverage.py
python/cairo-addons/src/cairo_addons/testing/fixtures.py
python/cairo-addons/src/cairo_addons/testing/runner.py

- **Add coverage fixture**
- **Add codecov to CI**

Add codecov

---

cairo/ethereum/cancun/blocks.cairo
cairo/ethereum/cancun/trie.cairo
cairo/tests/ethereum/cancun/test_trie.py
cairo/tests/ethereum/cancun/utils/test_message.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/strategies.py

feat: withdrawal trie

---

cairo/ethereum/cancun/vm/instructions/keccak.cairo
cairo/ethereum/cancun/vm/instructions/log.cairo
cairo/ethereum/cancun/vm/instructions/memory_instructions.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo

fix memory rebinding

---

cairo/ethereum/cancun/bloom.cairo
cairo/ethereum/utils/numeric.cairo
cairo/tests/ethereum/utils/test_numeric.py

Cov: uint64 from be bytes

---

cairo/ethereum/cancun/fork.cairo
cairo/ethereum/utils/numeric.cairo
cairo/ethereum_rlp/rlp.cairo
cairo/src/utils/bytes.cairo
cairo/tests/ethereum/utils/test_numeric.py

cov: numeric coverage

---

.github/workflows/python_tests.yml

ci: remove cache to fix coverage

---

cairo/tests/ethereum/cancun/vm/instructions/test_log.py
cairo/tests/utils/evm_builder.py
cairo/tests/utils/strategies.py

cov: log.cairo

---

cairo/tests/ethereum/cancun/vm/test_instructions.py

cov: instruction.cairo

---

cairo/tests/ethereum/cancun/test_fork_types.py

cov: fork_types

---

cairo/ethereum/cancun/vm/memory.cairo

cov: memory.cairo

---

cairo/tests/ethereum/cancun/vm/test_instructions.py

cov: instructions bis

---

.github/workflows/nightly_fuzzing.yml
.github/workflows/python_tests.yml

Add flags to codecov

---

cairo/ethereum/cancun/vm/instructions/storage.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_storage.py

fix: fuzz refund counter

---

cairo/ethereum/cancun/vm/instructions/block.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_block.py
cairo/tests/utils/strategies.py

dev: add append_logs util

---

cairo/ethereum/cancun/vm/gas.cairo
cairo/ethereum/cancun/vm/instructions/environment.cairo
cairo/ethereum/cancun/vm/instructions/keccak.cairo
cairo/ethereum/cancun/vm/instructions/memory_instructions.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo

dev: use native div by 32 on ceil32 values

---

cairo/ethereum/cancun/fork_types.cairo
cairo/ethereum/cancun/state.cairo
cairo/ethereum/cancun/trie.cairo
cairo/tests/ethereum/cancun/test_state.py
cairo/tests/ethereum/cancun/test_trie.py
cairo/tests/utils/args_gen.py

feat: state root

---

cairo/tests/ethereum/cancun/test_fork.py
cairo/tests/utils/strategies.py

cov: fork.cairo

---

cairo/ethereum/cancun/transactions.cairo
uv.lock

update exec specs for recover_sender

---

cairo/ethereum/cancun/fork.cairo
cairo/tests/ethereum/cancun/test_fork.py

fix: check_transaction

---

cairo/ethereum/cancun/state.cairo

fix: default value for Trie[Bytes32, U256]

---

python/cairo-addons/src/cairo_addons/hints/curve.py

Deserialize calldata for msm hint

---

cairo/ethereum/cancun/bloom.cairo
cairo/ethereum/cancun/state.cairo
cairo/ethereum/cancun/trie.cairo
cairo/ethereum/cancun/vm.cairo
cairo/ethereum/cancun/vm/interpreter.cairo
cairo/legacy/utils/dict.cairo
cairo/tests/ethereum/cancun/test_fork.py
cairo/tests/ethereum/cancun/test_trie.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/strategies.py
crates/cairo-addons/src/vm/dict_manager.rs

fix: use default_dict_finalize where necessary

---

cairo/ethereum/cancun/vm/precompiled_contracts/alt_bn128.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/mapping.cairo
cairo/ethereum/utils/numeric.cairo
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_alt_bn128.py
cairo/tests/ethereum/cancun/vm/test_interpreter.py
cairo/tests/utils/strategies.py
crates/cairo-addons/src/vm/hint_definitions/precompiles.rs
dictionary.txt
python/cairo-addons/src/cairo_addons/hints/precompiles.py

Needs modexp to be merged before to avoid merge conflicts
Closes #829 Closes #830

feat: ecpairing + ecadd + ec_mul unsound

---

cairo/ethereum/cancun/fork.cairo
cairo/ethereum/cancun/transactions.cairo
cairo/ethereum/cancun/vm/instructions.cairo
cairo/ethereum/cancun/vm/instructions/arithmetic.cairo
cairo/ethereum/cancun/vm/instructions/bitwise.cairo
cairo/ethereum/cancun/vm/instructions/block.cairo
cairo/ethereum/cancun/vm/instructions/comparison.cairo
cairo/ethereum/cancun/vm/instructions/control_flow.cairo
cairo/ethereum/cancun/vm/instructions/environment.cairo
cairo/ethereum/cancun/vm/instructions/keccak.cairo
cairo/ethereum/cancun/vm/instructions/log.cairo
cairo/ethereum/cancun/vm/instructions/memory_instructions.cairo
cairo/ethereum/cancun/vm/instructions/stack_instructions.cairo
cairo/ethereum/cancun/vm/instructions/storage.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/ethereum/cancun/vm/interpreter.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/alt_bn128.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/ecrecover.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/identity.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/mapping.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/modexp.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/sha256.cairo
cairo/ethereum/crypto/elliptic_curve.cairo
cairo/ethereum/exceptions.cairo
cairo/tests/ethereum/cancun/vm/instructions/test_system.cairo
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_ecrecover.py
cairo/tests/ethereum/cancun/vm/test_instructions.cairo
dictionary.txt
python/cairo-ec/src/cairo_ec/curve/secp256k1.cairo

had to modify all opcodes/precompile inputs to take the builtins required for ecrecover.
closes #804

feat: ecrecover precompile

---

cairo/ethereum/cancun/vm/precompiled_contracts/blake2f.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/mapping.cairo
cairo/ethereum_rlp/rlp.cairo
cairo/legacy/utils/utils.cairo
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_blake2f.py
cairo/tests/ethereum/cancun/vm/test_interpreter.py
dictionary.txt

feat: blake2f

---

cairo/ethereum/cancun/vm/precompiled_contracts/mapping.cairo
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_mapping.py

fix: precompile lookup

---

.github/workflows/nightly_fuzzing.yml
.github/workflows/push.yml
.github/workflows/python_tests.yml
cairo/tests/ethereum/cancun/test_fork.py
uv.lock

Complex strategies are causing problems in nigthly.
Ef-tests will replace those.
Closes #808

test: remove fuzzing check transaction

---

cairo/ethereum/cancun/vm/precompiled_contracts/alt_bn128.cairo
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_alt_bn128.py
conftest.py
crates/cairo-addons/src/vm/hint_definitions/curve.rs
python/cairo-addons/src/cairo_addons/hints/curve.py
python/cairo-ec/src/cairo_ec/circuits/ec_ops.cairo
python/cairo-ec/src/cairo_ec/circuits/ec_ops_compiled.cairo
python/cairo-ec/src/cairo_ec/curve/g1_point.cairo
python/cairo-ec/src/cairo_ec/ec_ops.cairo
python/cairo-ec/src/cairo_ec/uint384.cairo
python/cairo-ec/tests/circuits/test_circuits.cairo
python/cairo-ec/tests/circuits/test_circuits.py
python/cairo-ec/tests/test_ec_ops.py

feat: ec add

---

python/cairo-ec/src/cairo_ec/circuits/mod_ops.cairo
python/cairo-ec/src/cairo_ec/circuits/mod_ops_compiled.cairo
python/cairo-ec/src/cairo_ec/curve/secp256k1.cairo
python/cairo-ec/src/cairo_ec/uint384.cairo
python/cairo-ec/tests/circuits/test_circuits.cairo
python/cairo-ec/tests/circuits/test_circuits.py
python/cairo-ec/tests/test_uint384.cairo
python/cairo-ec/tests/test_uint384.py

This code was entirely LLM generated. I did not touch a single line. I wanted to experiment on a semi-automated Issue -> PR pipeline 
Closes https://github.com/kkrt-labs/keth/issues/856

feat: add new assert circuits

---

cairo/ethereum/cancun/vm/precompiled_contracts/blake2f.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/mapping.cairo
cairo/ethereum/cancun/vm/precompiled_contracts/ripemd160.cairo
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_ripemd160.py
dictionary.txt

feat: ripemd160

---

Cargo.lock
Cargo.toml
rust-toolchain

With a fix of the modbuiltin runner bug

dev: update cairovm

---

cairo/tests/ethereum/cancun/test_fork.py
cairo/tests/ethereum/cancun/vm/test_gas.py
cairo/tests/ethereum/crypto/test_hash.py
crates/cairo-addons/src/vm/hint_definitions/dict.rs
python/cairo-core/tests/src/cairo_core/test_maths.py

tests: review assumes

---

cairo/ethereum/cancun/vm/interpreter.cairo

fix: off-by-one error in codesize checks

---

cairo/ethereum/cancun/vm/instructions/control_flow.cairo

fix: check jumpdest high

---

cairo/ethereum/cancun/vm/instructions/environment.cairo
cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/ethereum/utils/hash_dicts.cairo

Part of https://github.com/kkrt-labs/keth/issues/776

refactor: set_address_contains_or_add

---

cairo/ethereum/cancun/vm/interpreter.cairo

fix: transient storage rebinding

---

cairo/scripts/zkpi_to_eels.py
crates/cairo-addons/src/vm/runner.rs
python/cairo-addons/src/cairo_addons/testing/runner.py
scripts/extract_cycles.sh

- **Handle None to in normalize**
- **Split verification in several calls**
- **Fix ancestors order**
Solves: #890

Fix zkpi to eels

---

cairo/ethereum/cancun/vm/instructions/system.cairo
cairo/ethereum/utils/hash_dicts.cairo

Part of https://github.com/kkrt-labs/keth/issues/776

refactor: SetAddress add

---

cairo/ethereum/cancun/utils/message.cairo
crates/cairo-addons/src/vm/hint_definitions/hashdict.rs
python/cairo-addons/src/cairo_addons/hints/hashdict.py

fix: precompiles warmup

---

cairo/ethereum/cancun/vm/instructions/environment.cairo
cairo/legacy/utils/bytes.cairo

Side effect: delete dead code keccak function

refactor: use U256_from_be_bytes32 for code_hash

---

cairo/ethereum/cancun/vm/runtime.cairo

fix off by one in validate

---

cairo/ethereum/cancun/vm.cairo
cairo/ethereum/cancun/vm/interpreter.cairo
cairo/ethereum/cancun/vm/runtime.cairo
cairo/tests/ethereum/cancun/vm/test_runtime.cairo
cairo/tests/ethereum/cancun/vm/test_runtime.py
crates/cairo-addons/src/vm/hint_definitions/utils.rs
python/cairo-addons/src/cairo_addons/hints/utils.py

fix: assertion on OOB valid jumpdests

---

crates/cairo-addons/src/vm/hint_definitions/hashdict.rs

The suggestion in comment of PR #925  for this hint was erroneous: it skipped the non-int values (when the associated value was a pointer) whereas it should have returned the prefix instead.

fix: get_storage_keys_for_address

---

python/cairo-ec/src/cairo_ec/curve/secp256k1.cairo

fix point at infinity

---

cairo/ethereum/cancun/vm/gas.cairo
cairo/ethereum/cancun/vm/instructions/environment.cairo
cairo/ethereum_rlp/rlp.cairo
cairo/tests/ef_tests/helpers/load_state_tests.py
python/cairo-addons/src/cairo_addons/testing/hooks.py

fix: blob-related ef-tests failures

---

cairo/ethereum/cancun/fork.cairo
cairo/ethereum/cancun/vm/gas.cairo
cairo/ethereum/cancun/vm/interpreter.cairo
cairo/tests/conftest.py
conftest.py

https://github.com/kkrt-labs/keth/issues/932
Made with ❤️ by Claude Code
@obatirou this fixes the issue you had with `uv run pytest -k "test_name"` which now properly supports our logger patches

dev: custom logger formats

---

python/cairo-addons/src/cairo_addons/hints/injected.py
python/cairo-addons/src/cairo_addons/testing/runner.py

dev: enable serialize in python vm hints

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
cairo/tests/test_serde.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py
dictionary.txt

feat: BNF12

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py
dictionary.txt

feat: BNP12

---

.cursor/mcp.json
.env.example
dictionary.txt

Updates the dictionary and adds Cursor configuration files.
You can check (and enable) MCP in the cursor settings (not the VS code settings, not the cmd+,)
See also https://docs.cursor.com/context/model-context-protocol

chore: update dictionary and cursor config

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/ethereum/utils/numeric.cairo
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py

refactor: use U384 for BNF12

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: bnf12 from_int

---

cairo/ethereum/cancun/vm/precompiled_contracts/alt_bn128.cairo
cairo/ethereum/utils/numeric.cairo
cairo/ethereum_types/numeric.cairo
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
crates/cairo-addons/src/vm/hint_definitions/curve.rs
crates/cairo-addons/src/vm/runner.rs
python/cairo-addons/src/cairo_addons/hints/circuits.py
python/cairo-addons/src/cairo_addons/hints/curve.py
python/cairo-core/src/cairo_core/numeric.cairo
python/cairo-ec/src/cairo_ec/curve/__init__.py
python/cairo-ec/src/cairo_ec/curve/g1_point.cairo
python/cairo-ec/src/cairo_ec/curve/secp256k1.cairo
python/cairo-ec/src/cairo_ec/ec_ops.cairo
python/cairo-ec/src/cairo_ec/uint384.cairo
python/cairo-ec/tests/curve/test_secp256k1.cairo
python/cairo-ec/tests/test_ec_ops.cairo
python/cairo-ec/tests/test_ec_ops.py
python/cairo-ec/tests/test_uint384.cairo

refactor: g1 point struct & support in serde

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py

feat: BNF2 and BNF2 addition

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: BNF2 multiplication

---

.env.example
.github/workflows/python_tests.yml
cairo/scripts/zkpi_to_eels.py
python/eth-rpc/pyproject.toml
python/eth-rpc/src/eth_rpc/client.py
python/mpt/pyproject.toml
python/mpt/src/mpt/ethereum_tries.py
python/mpt/src/mpt/utils.py
python/mpt/tests/test_ethereum_tries.py
uv.lock

- a ethereum tries function called `to_state` that traverses the ethereum tries to construct a state object
- a test that attempts to run EELS' `state_transition` on this newly constructed state object
closes #1028

feat: convert ethereum MPT to EELS state

---

cairo/ethereum/cancun/vm/precompiled_contracts/modexp.cairo
cairo/ethereum/crypto/alt_bn128.cairo
cairo/ethereum/utils/numeric.cairo
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_modexp.py
cairo/tests/ethereum/crypto/test_alt_bn128.py
cairo/tests/ethereum/utils/test_numeric.py

feat: bnf12 pow

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: BNF12__eq__ and bnf2_to_bnf12

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: bnf12_frobenius

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

Closes #987 
Closes #986 
Closes #992

feat: BNP12 eq, point at infinity and from BNP

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: twist

---

python/cairo-ec/tests/circuits/test_circuits.py

fix: test_sum_ratio

---

Cargo.lock
cairo/ethereum/crypto/alt_bn128.cairo
cairo/ethereum/utils/numeric.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
crates/cairo-addons/Cargo.toml
crates/cairo-addons/src/vm/hint_definitions.rs
crates/cairo-addons/src/vm/hint_definitions/crypto.rs
crates/cairo-addons/src/vm/hint_definitions/curve.rs
crates/cairo-addons/src/vm/hints.rs
dictionary.txt
python/cairo-addons/src/cairo_addons/hints/__init__.py
python/cairo-addons/src/cairo_addons/hints/crypto.py

Closes #1065 
Introduces `BNF2_ONE()`, similar to `BNF2_ZERO()` as well as `bnf2__eq__()`
WIP: Hints are yet to be finished

feat: bnf2 div

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: bnp2 mul_by

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
uv.lock

Closes #1089 
Closes #1064 
Closes #1043
Update the exec specs to generalize the infinity point check in double method 
https://github.com/ethereum/execution-specs/commit/516345727a74f59db8f9c8e2bb0e5199d2ada1f7

feat: BNF2 sub and BNP2 double

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

Closes #1063 
Note: https://github.com/kkrt-labs/keth/pull/1098 was merged in the current branch instead of main

feat: bnp2 add

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: bnp2 init

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: BNP12 init

---

cairo/ethereum_rlp/rlp.cairo
cairo/tests/ethereum_rlp/test_rlp.py

feat: Extended__eq__ util

---

cairo/tests/ethereum/crypto/test_alt_bn128.py

fix: fix nightly CI

---

cairo/ethereum/cancun/trie.cairo
cairo/tests/ethereum/cancun/test_trie.py
python/mpt/pyproject.toml
python/mpt/src/mpt/ethereum_tries.py
python/mpt/src/mpt/trie_diff.py
python/mpt/src/mpt/utils.py
python/mpt/tests/test_utils.py

feat: `nibble_list_to_bytes`

---

cairo/ethereum/utils/bytes.cairo
cairo/tests/ethereum/utils/test_bytes.py
python/mpt/src/mpt/trie_diff.py

feat: Bytes__add__ + Bytes__extend__

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
crates/cairo-addons/src/vm/hint_definitions/crypto.rs
dictionary.txt
python/cairo-addons/src/cairo_addons/hints/crypto.py

Closes #999 
Closes #979 
rust hint not implemented here, see #1127

feat: add bnf12 div

---

.env.example
.github/workflows/push.yml
.github/workflows/python_tests.yml
cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
dictionary.txt
pyproject.toml
uv.lock

feat: final exponentiation from garaga-zero

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
cairo/tests/utils/strategies.py

Closes #989 
Closes https://github.com/kkrt-labs/keth/issues/1069

feat: bnp12 double

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: implement bnp12 add

---

cairo/tests/utils/args_gen.py

fix: refund_counter EVM__eq__ when negative

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: bnp12 mul by

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
dictionary.txt

feat: linefunc

---

python/mpt/src/mpt/trie_diff.py

- fix the case where a leaf node does not share any key segment with an extension node

fix trie_diff python for ext vs. leaf edge cases

---

cairo/tests/ef_tests/helpers/load_state_tests.py

fix: runresources string matching

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py

feat: add alt_bn128 pairing

---

.github/actions/setup-environment/action.yaml
Cargo.lock
Cargo.toml
cairo/scripts/prove_block.py
crates/cairo-addons/Cargo.toml
crates/cairo-addons/src/vm/runner.rs

fix: restore prove_block script

---

python/mpt/src/mpt/trie_diff.cairo
python/mpt/tests/src/mpt/test_trie_diff.cairo
python/mpt/tests/src/mpt/test_trie_diff.py

feat: preimage check on storage keys

---

python/mpt/src/mpt/trie_diff.cairo
python/mpt/tests/src/mpt/test_trie_diff.cairo
python/mpt/tests/src/mpt/test_trie_diff.py

feat: add preimage hashing checks on mpt addresses

---

python/cairo-ec/src/cairo_ec/curve/alt_bn128.cairo
python/cairo-ec/src/cairo_ec/curve/bls12_381.cairo
python/cairo-ec/src/cairo_ec/curve/secp256k1.cairo
python/cairo-ec/tests/curve/test_alt_bn128.cairo
python/cairo-ec/tests/curve/test_alt_bn128.py
python/cairo-ec/tests/curve/test_bls12_381.cairo
python/cairo-ec/tests/curve/test_bls12_381.py
python/cairo-ec/tests/curve/test_secp256k1.cairo
python/cairo-ec/tests/curve/test_secp256k1.py

feat: add BLS12-381 curve

---

cairo/tests/test_hint_runner.cairo
cairo/tests/test_hint_runner.py
crates/cairo-addons/src/vm/vm_consts.rs

Closes https://github.com/kkrt-labs/keth/issues/1040

fix: pointer member addresses in rustvm ids object

---

python/cairo-addons/pyproject.toml
python/cairo-core/pyproject.toml
python/cairo-ec/pyproject.toml
python/mpt/pyproject.toml
python/mpt/src/mpt/trie_diff.py

Put same known first party everywhere and update file tree

---

cairo/ethereum/crypto/kzg.cairo
cairo/tests/ethereum/crypto/test_kzg.py
cairo/tests/test_serde.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py
python/cairo-ec/tests/curve/test_bls12_381.py

feat: bytes_to_bls_field

---

cairo/ethereum/crypto/kzg.cairo
cairo/tests/ethereum/crypto/test_kzg.py

Closes [1178](https://github.com/kkrt-labs/keth/issues/1178)

feat: os2ip

---

cairo/ethereum/crypto/kzg.cairo
cairo/tests/ethereum/crypto/test_kzg.py

feat: get_flags

---

Cargo.lock
cairo/ethereum/crypto/bls12_381.cairo
cairo/tests/ethereum/crypto/test_bls12_381.py
cairo/tests/test_serde.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py
crates/cairo-addons/Cargo.toml
crates/cairo-addons/src/vm/hint_definitions/crypto.rs
dictionary.txt
python/cairo-addons/src/cairo_addons/hints/crypto.py
python/cairo-ec/src/cairo_ec/curve/__init__.py

Closes #1188 
Closes #1185 
The `blsf_div` and `blsf2_div` have ~~not~~ been implemented, it can be done in this PR if needed ✅ .

feat: add bls12-381 field ops for base and quadratic extension fields

---

python/mpt/src/mpt/hash_diff.cairo
python/mpt/src/mpt/utils.py
python/mpt/tests/src/mpt/test_hash_diff.py

feat: add hash methods to DiffEntry structs

---

cairo/ethereum/crypto/kzg.cairo
cairo/ethereum_types/bytes.cairo
cairo/tests/ethereum/crypto/test_kzg.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py
python/cairo-core/src/cairo_core/bytes.cairo

feat: kzg_commitment_to_versioned_hash

---

cairo/ethereum/crypto/hash.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
crates/cairo-addons/src/vm/hint_definitions/mpt.rs
python/cairo-addons/src/cairo_addons/hints/mpt.py
python/mpt/src/mpt/trie_diff.cairo
python/mpt/src/mpt/types.cairo
python/mpt/src/mpt/utils.cairo
python/mpt/tests/src/mpt/test_hash_diff.py
python/mpt/tests/src/mpt/test_utils.py

feat: sort memory segment

---

cairo/ethereum/crypto/bls12_381.cairo
cairo/tests/ethereum/crypto/test_bls12_381.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py

Closes #1187 
Closes #1168 
Closes #1186

feat: BLSP and BLSP2 structs and ops

---

cairo/ethereum/cancun/fork.cairo
cairo/ethereum/cancun/state.cairo
cairo/tests/utils/serde.py

fix: correctly finalize state at end of block

---

cairo/ethereum/cancun/fork_types.cairo
cairo/ethereum/cancun/state.cairo
cairo/ethereum_rlp/rlp.cairo
cairo/scripts/prove_block.py
cairo/tests/ethereum_rlp/test_rlp.py
cairo/tests/test_serde.cairo
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
conftest.py
python/cairo-addons/src/cairo_addons/testing/compiler.py
python/mpt/src/mpt/ethereum_tries.py
python/mpt/src/mpt/hash_diff.cairo
python/mpt/src/mpt/trie_diff.cairo
python/mpt/src/mpt/trie_diff.py
python/mpt/src/mpt/types.cairo
python/mpt/src/mpt/utils.cairo
python/mpt/src/mpt/utils.py
python/mpt/tests/src/mpt/test_hash_diff.py
python/mpt/tests/src/mpt/test_trie_diff.cairo
python/mpt/tests/src/mpt/test_trie_diff.py
python/mpt/tests/src/mpt/test_utils.py

Closes https://github.com/kkrt-labs/keth/issues/1245

dev: merge AccountNode and Account types

---

cairo/tests/utils/args_gen.py
python/mpt/src/mpt/hash_diff.cairo
python/mpt/src/mpt/trie_diff.cairo
python/mpt/src/mpt/types.cairo

feat: optional account in account diff

---

python/mpt/src/mpt/trie_diff.cairo
python/mpt/src/mpt/trie_diff.py
python/mpt/src/mpt/utils.cairo
python/mpt/src/mpt/utils.py
python/mpt/tests/src/mpt/test_utils.py

feat: add checks on well-formed leaves

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/ethereum/crypto/bls12_381.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
cairo/tests/ethereum/crypto/test_bls12_381.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/strategies.py
pyproject.toml
uv.lock

fix: handle point at infinity case in bnp init and blsp init

---

crates/cairo-addons/src/vm/runner.rs
python/mpt/src/mpt/trie_diff.cairo
python/mpt/src/mpt/utils.cairo
python/mpt/src/mpt/utils.py
python/mpt/tests/src/mpt/test_utils.py

feat: check extension nodes well formed

---

cairo/scripts/prove_block.py
conftest.py

Closes https://github.com/kkrt-labs/keth/issues/1274

fix: patch EELS set_code where its used

---

python/mpt/src/mpt/hash_diff.cairo

hash 0 if storage is deleted or created

---

cairo/tests/ethereum/crypto/test_bls12_381.py

fix: make harder assumptions in test_blsp_init_fails

---

cairo/ethereum/crypto/bls12_381.cairo
cairo/ethereum/crypto/kzg.cairo
cairo/tests/ethereum/crypto/test_kzg.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py
python/cairo-addons/src/cairo_addons/hints/crypto.py

feat: decompress g1

---

crates/cairo-addons/src/vm/hint_definitions/mpt.rs
python/mpt/src/mpt/utils.cairo
python/mpt/tests/src/mpt/test_utils.py

fix: sort state diff keys in ascending order

---

.github/actions/setup-environment/action.yaml
python/mpt/tests/test_ethereum_tries.py

Tentative to fix caching issues

ci: bump uv action version

---

cairo/ethereum/crypto/kzg.cairo
cairo/tests/ethereum/crypto/test_kzg.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py

feat: pubkey_to_G1

---

cairo/ethereum/crypto/kzg.cairo
cairo/tests/ethereum/crypto/test_kzg.py

feat: is_inf and subgroup_check

---

cairo/ethereum/crypto/bls12_381.cairo
cairo/ethereum/crypto/kzg.cairo
cairo/tests/ethereum/crypto/test_bls12_381.py
cairo/tests/ethereum/crypto/test_kzg.py
dictionary.txt
python/cairo-addons/src/cairo_addons/hints/crypto.py

feat: key validate

---

cairo/ethereum/crypto/kzg.cairo
cairo/tests/ethereum/crypto/test_kzg.py

feat: validate_kzg_g1 and bytes_to_kzg_commitment

---

cairo/tests/test_hint_runner.cairo
cairo/tests/test_hint_runner.py
crates/cairo-addons/src/vm/vm_consts.rs

Closes #1297
Might close #1279

fix: ids object construction on casted types

---

cairo/ethereum/cancun/fork.cairo
cairo/ethereum/cancun/main.cairo
cairo/ethereum/cancun/state.cairo
cairo/scripts/prove_block.py
cairo/tests/ef_tests/helpers/load_state_tests.py
cairo/tests/ethereum/cancun/test_main.py
cairo/tests/utils/args_gen.py
cairo/utils/fixture_loader.py
crates/cairo-addons/README.md
crates/cairo-addons/src/vm/runner.rs
python/mpt/src/mpt/ethereum_tries.py
python/mpt/src/mpt/hash_diff.cairo

feat: use zkpi prestate and non-default state dicts

---

cairo/ethereum/cancun/vm/precompiled_contracts/alt_bn128.cairo
cairo/ethereum/crypto/alt_bn128.cairo
cairo/tests/ethereum/crypto/test_alt_bn128.py
pyproject.toml
uv.lock

feat: pairing with crypto/altbn128

---

cairo/ethereum/crypto/bls12_381.cairo
cairo/ethereum/crypto/kzg.cairo
cairo/tests/ethereum/crypto/test_bls12_381.py
cairo/tests/ethereum/crypto/test_kzg.py
cairo/tests/test_serde.py
cairo/tests/utils/args_gen.py
cairo/tests/utils/serde.py
cairo/tests/utils/strategies.py
dictionary.txt

feat: pairing_check

---

cairo/ethereum/crypto/kzg.cairo
cairo/tests/ethereum/crypto/test_kzg.py

feat: verify_kzg_proof

---

.trunk/trunk.yaml
cairo/tests/ethereum/cancun/test_trie.py
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_mapping.py
cairo/tests/ethereum/crypto/test_alt_bn128.py
cairo/tests/ethereum/crypto/test_bls12_381.py
cairo/tests/ethereum/utils/test_bytes.py
cairo/tests/legacy/utils/test_bytes_legacy.py
cairo/tests/legacy/utils/test_dict.py
cairo/tests/test_hint_runner.cairo
cairo/tests/test_hint_runner.py
crates/cairo-addons/src/vm/hint_definitions/mpt.rs
crates/cairo-addons/src/vm/program.rs
crates/cairo-addons/src/vm/pythonic_hint.rs
crates/cairo-addons/src/vm/runner.rs
crates/cairo-addons/src/vm/vm_consts.rs
pyproject.toml
python/cairo-addons/src/cairo_addons/hints/curve.py
python/cairo-addons/src/cairo_addons/hints/ethereum.py
python/cairo-addons/src/cairo_addons/hints/hashdict.py
python/cairo-addons/src/cairo_addons/hints/injected.py
python/cairo-addons/src/cairo_addons/hints/maths.py
python/cairo-addons/src/cairo_addons/hints/precompiles.py
python/cairo-addons/src/cairo_addons/testing/hints.py
python/cairo-core/tests/src/cairo_core/test_comparison.py
python/cairo-core/tests/src/cairo_core/test_maths.py
python/mpt/tests/src/mpt/test_trie_diff.py
python/mpt/tests/src/mpt/test_utils.py

closes https://github.com/kkrt-labs/keth/issues/1225

feat: add patch_hint support on rustvm

---

cairo/ethereum/crypto/kzg.cairo
cairo/ethereum/utils/numeric.cairo
cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_modexp.py
cairo/tests/ethereum/utils/test_numeric.py

feat: U384_to_le_bytes

---

cairo/ethereum/crypto/alt_bn128.cairo
cairo/ethereum/crypto/bls12_381.cairo
cairo/ethereum/crypto/kzg.cairo
cairo/ethereum/utils/numeric.cairo

dev: eq return bool bls

---

.github/workflows/push.yml

fix: reduce parallelism in main job

---

cairo/tests/ethereum/crypto/test_alt_bn128.py

refactor: remove unnecessary checks test_pairing

---

codecov.yml

closes https://github.com/kkrt-labs/keth/issues/1198

fix codecov threshold

---

cairo/tests/test_hint_runner.cairo
cairo/tests/test_hint_runner.py
crates/cairo-addons/src/vm/runner.rs
docs/AI-REPORT.md
python/cairo-addons/src/cairo_addons/hints/injected.py
python/cairo-addons/src/cairo_addons/testing/hints.py
python/cairo-addons/src/cairo_addons/testing/runner.py

feat: debug_info passed in rust runner

---

cairo/tests/test_hint_runner.cairo
cairo/tests/test_hint_runner.py
crates/cairo-addons/src/vm/vm_consts.rs

add [ ] operator to vmconst rust

---

cairo/tests/utils/serde.py
crates/cairo-addons/src/vm/runner.rs
python/cairo-addons/src/cairo_addons/testing/hooks.py
python/cairo-addons/src/cairo_addons/testing/runner.py
python/keth-types/pyproject.toml

Closes https://github.com/kkrt-labs/keth/issues/1396

dev: support arbitrary argument order in runner

---

codecov.yml
python/cairo-addons/src/cairo_addons/testing/errors.py
python/cairo-core/src/cairo_core/control_flow.cairo
python/mpt/src/mpt/ethereum_tries.py
python/mpt/src/mpt/trie_builder.py
python/mpt/src/mpt/trie_diff.cairo
python/mpt/src/mpt/trie_diff.py
python/mpt/src/mpt/utils.cairo
python/mpt/src/mpt/utils.py
python/mpt/tests/src/mpt/test_trie_builder.py
python/mpt/tests/src/mpt/test_trie_diff.py
python/mpt/tests/src/mpt/test_utils.py

tests: invalid mpt

---

cairo/ethereum/cancun/blocks.cairo
cairo/ethereum/cancun/fork_types.cairo
cairo/ethereum/cancun/transactions_types.cairo
cairo/ethereum/utils/numeric.cairo
cairo/tests/ethereum/cancun/test_blocks.py
cairo/tests/ethereum/cancun/test_fork_types.py
cairo/tests/ethereum/cancun/test_transactions_types.py
cairo/tests/ethereum/utils/test_numeric.py
cairo/tests/utils/hash_utils.py
python/cairo-core/src/cairo_core/bytes_impl.cairo
python/cairo-core/tests/src/cairo_core/test_bytes_impl.py

Adds __hash__ functions using blake2s.
Closes #1366

feat: blake2s hash commitment utils

---

cairo/ethereum/cancun/blocks.cairo
cairo/tests/ethereum/cancun/test_blocks.py
cairo/tests/utils/hash_utils.py
python/cairo-core/pyproject.toml
python/cairo-core/src/cairo_core/bytes_impl.cairo
python/cairo-core/tests/src/cairo_core/test_bytes_impl.py

feat: block blake2s commitments

---

README.md
cairo/ethereum/cancun/fork.cairo
cairo/ethereum/cancun/init.cairo
cairo/ethereum/cancun/state.cairo
cairo/ethereum/cancun/trie.cairo
cairo/ethereum/crypto/hash.cairo
cairo/scripts/compile_cairo.py
cairo/scripts/keth.py
cairo/tests/ethereum/cancun/test_init.cairo
cairo/tests/ethereum/cancun/test_init.py
crates/cairo-addons/src/vm/hint_definitions/hashdict.rs
python/cairo-addons/src/cairo_addons/hints/hashdict.py

feat: create init.cairo

---

dictionary.txt
pyproject.toml
python/cairo-lint/README.md
python/cairo-lint/pyproject.toml
python/cairo-lint/src/cairo_lint/main.py
python/cairo-lint/tests/test_data/all_used.cairo
python/cairo-lint/tests/test_data/disabled_file.cairo
python/cairo-lint/tests/test_data/disabled_line_multi_block.cairo
python/cairo-lint/tests/test_data/disabled_line_multi_item.cairo
python/cairo-lint/tests/test_data/disabled_line_single.cairo
python/cairo-lint/tests/test_data/multi_comma_last.cairo
python/cairo-lint/tests/test_data/multi_comma_last_expected.cairo
python/cairo-lint/tests/test_data/no_imports.cairo
python/cairo-lint/tests/test_data/unused_multi_one.cairo
python/cairo-lint/tests/test_data/unused_multi_one_expected.cairo
python/cairo-lint/tests/test_data/unused_single.cairo
python/cairo-lint/tests/test_data/unused_single_expected.cairo
python/cairo-lint/tests/test_data/unused_single_partial.cairo
python/cairo-lint/tests/test_data/unused_single_partial_expected.cairo
python/cairo-lint/tests/test_format.py
uv.lock

dev: add cairo-lint CLI

---

python/mpt/src/mpt/ethereum_tries.py

fix: sload on null acct

---

cairo/ethereum/cancun/keth/body.cairo
cairo/ethereum/cancun/keth/body_main.cairo
cairo/ethereum/cancun/keth/commitments.cairo
cairo/ethereum/cancun/keth/init.cairo
cairo/ethereum/cancun/keth/main.cairo
cairo/ethereum/cancun/keth/teardown.cairo
cairo/tests/ethereum/cancun/keth/test_teardown.py

Closes https://github.com/kkrt-labs/keth/issues/1434

refactor: stop patricializing state for commitments

---

cairo/ethereum/cancun/keth/body.cairo
cairo/ethereum/cancun/keth/commitments.cairo
cairo/ethereum/cancun/keth/init.cairo
cairo/ethereum/cancun/keth/teardown.cairo
cairo/ethereum/cancun/vm.cairo
cairo/ethereum/cancun/vm/env_impl.cairo
cairo/tests/utils/hash_utils.py
cairo/utils/fixture_loader.py
python/cairo-addons/src/cairo_addons/hints/main.py
python/cairo-core/src/cairo_core/bytes_impl.cairo
python/cairo-core/tests/src/cairo_core/test_bytes_impl.py

Migrates commitments to the new input expected post-EELS migration

migrate commitments

---

cairo/scripts/test_keth_cli.py
crates/cairo-addons/src/vm/runner.rs

fix: generate run outputs in e2e steps
