- bin/keth/src/cli/mod.rs
- bin/keth/src/main.rs
Allow to set the block time of the node and run with the default `AutoSealConsensus` which automatically seals a block.
> feat: block time

- Cargo.lock
- Cargo.toml
- bin/keth/Cargo.toml
- crates/node/src/node.rs
In order to avoid moving the `Cargo.lock` at each compilation, we chose to use a fixed version of reth. 
Latest is `1.0.6`.
Related https://github.com/paradigmxyz/reth/releases/tag/v1.0.6
> deps: use reth release 1.0.6

- crates/exex/src/db.rs
- crates/pool/src/validate/mod.rs
We want to be generic at a node level and enforce specific rules at ExEx level.
> rm `no_eip4844` in tx pool

- cairo_programs/compile_cairo.py
- cairo_programs/fibonacci.json
- cairo_programs/transaction_hash.json
- crates/exex/src/db.rs
- crates/exex/src/exex.rs
In the scope of this PR:
- Compile the Cairo programs in proof mode
- Run the Cairo VM in proof mode
- Store in the db the air private and public input with the aim of using them to run the prover (see https://github.com/dipdup-io/stone-packaging/tree/master)
> run cairo-vm in proof mode and store AIR inputs

- crates/exex/src/model.rs
> model: impl `From<U256>` for `KethU256`

- crates/exex/src/model.rs
> model: impl `From<Bytes>` for `KethPointer`

- cairo/programs/os.json
- cairo/src/utils/compile_cairo.py
The json file generated by `cairo-compile` is not trunk-compliant.
Because we commit the compiled os.json file, we need to make sure it's trunk-compliant.
Added a `trunk fmt` command to the `compile_cairo.py` script.
Run `uv run compile` to compile and format the main `os.cairo`.
> Add trunk fmt after cairo compile

- Cargo.lock
- cairo/programs/fork.cairo
- cairo/tests/fixtures/data.py
- cairo/tests/programs/test_fork.cairo
- cairo/tests/programs/test_fork.py
- cairo/tests/utils/models.py
- cairo/tests/utils/parsers.py
In order to make sure that keth closely follows the ethereum spec, we need to make sure that the fork rules are correctly implemented.
One of the best way to do this is to work with diff testing.
Refactor the codebase to be closer to the execution spec and diff test every function.
Create a file structure that mimics the one in the execution specs and implement the required functions in order.
This PR starts with the `validate_header` function.
> Implement and diff-test validate_header

- cairo/programs/fork.cairo
- cairo/src/gas.cairo
- cairo/src/instructions/system_operations.cairo
- cairo/src/interpreter.cairo
- cairo/src/state.cairo
- cairo/src/utils/maths.cairo
- cairo/src/utils/transaction.cairo
- cairo/tests/fixtures/data.py
- cairo/tests/programs/test_fork.cairo
- cairo/tests/programs/test_fork.py
- cairo/tests/src/test_gas.cairo
- cairo/tests/src/test_gas.py
- cairo/tests/src/utils/test_math.cairo
- cairo/tests/src/utils/test_math.py
- cairo/tests/utils/hints.py
- cairo/tests/utils/models.py
- cairo/tests/utils/parsers.py
- cairo/tests/utils/strategies.py
Implement `calculate_intrinsic_cost`.
See https://github.com/ethereum/execution-specs/blob/master/src/ethereum/cancun/fork.py#L818-L862
> Add intrinsic gas cost diff testing

- cairo/src/utils/transaction.cairo
- cairo/tests/src/utils/test_transaction.py
- cairo/tests/utils/constants.py
Closes #155
Fixes potential OOB reads for malformed access lists.
> fix: OOB read in parse_storage_keys on malformed inputs

- cairo/src/utils/utils.cairo
- cairo/tests/src/utils/test_utils.cairo
- cairo/tests/src/utils/test_utils.py
- cairo/tests/utils/dict.cairo
- cairo/tests/utils/hints.py
- solidity_contracts/src/mocks/Counter.sol
Closes #158
Avoids a malicious prover to continue iterating over the bytecode limit and consuming extra resources, but has no impact over code execution
> fix: underconstrained initialize_jumpdests

- cairo/src/precompiles/ripemd160.cairo
- cairo/tests/src/precompiles/test_ripemd160.py
> fix: off by one error ripemd-160

- cairo/src/utils/transaction.cairo
- cairo/tests/src/utils/test_transaction.py
- cairo/tests/utils/errors.py
Closes #148
Adds missing constraint in `decode_legacy_tx` to ensure there is no overflow for `chain_id`
> fix: decode legacy chain id overflow

- cairo/src/utils/bytes.cairo
- cairo/tests/src/utils/test_bytes.py
Closes https://github.com/kkrt-labs/keth/issues/145
Add a missing constraint to ensure `bytes_len` cannot be greater to `31` in `felt_to_bytes_little`
> fix: felt_to_bytes_little loop stop condition

- cairo/src/constants.cairo
Close #162
Several of the stack_size_diff values defined in constants.cairo are off put the right values.
> fix: stack_size_diff

- cairo/src/utils/transaction.cairo
- cairo/tests/programs/test_os.py
Closes #161
Fixes the checks on s value when recovering the transaction sender.
> fix: validate s <= N//2 when recovering tx sender

- cairo/ethereum/cancun/trie.cairo
- cairo/tests/ethereum/cancun/test_trie.py
- cairo/tests/utils/hints.py
Closes https://github.com/kkrt-labs/keth/issues/212
Closes https://github.com/kkrt-labs/keth/issues/214
- Adds a constraint that `(x.value.len - remainder) / 2;` is in range [0, range_check[; if it doesn't, the prover has provided a wrong value.
- Adds support to patch `nondet` hints.
> fix: add constraint on nibbles

- cairo/src/utils/signature.cairo
- cairo/src/utils/transaction.cairo
- cairo/tests/src/utils/test_signature.cairo
- cairo/tests/src/utils/test_signature.py
Closes #163
Ensure y_parity is 0 or 1. Adds also missing tests.
> fix: ensure y_parity is 0 or 1

- cairo/src/instructions/system_operations.cairo
> dev: remove dead code in exec_create

- cairo/src/gas.cairo
- cairo/tests/src/test_gas.cairo
- cairo/tests/src/test_gas.py
Closes #156
Test for gas were imported from Kakarot, a refactor was done to use strategies.py
>  fix: memory expansion early return condition

- cairo/src/instructions/system_operations.cairo
> fix: Selfdestruct send to burn address

- cairo/programs/os.cairo
- cairo/tests/programs/test_os.py
- cairo/tests/utils/data.py
> fix: Ensure sender nonce does not overflow

- .trunk/trunk.yaml
Adds the pre-push trunk hook back, to avoid cases where CI fails because of a lint check
> dev: add pre-push trunk hook

- cairo/src/precompiles/ec_recover.cairo
- cairo/src/utils/signature.cairo
- cairo/tests/ethereum/cancun/test_trie.py
- cairo/tests/fixtures/runner.py
- cairo/tests/src/precompiles/test_ec_recover.py
- cairo/tests/src/utils/test_signature.cairo
- cairo/tests/src/utils/test_signature.py
- cairo/tests/utils/strategies.py
> feat: use KeccakBuiltin for address recovery and signature verification

- cairo/programs/os.cairo
- cairo/src/account.cairo
- cairo/src/evm.cairo
- cairo/src/instructions/memory_operations.cairo
- cairo/src/instructions/system_operations.cairo
- cairo/src/interpreter.cairo
- cairo/src/model.cairo
- cairo/tests/src/instructions/test_duplication_operations.cairo
- cairo/tests/src/instructions/test_environmental_information.cairo
- cairo/tests/src/instructions/test_exchange_operations.cairo
- cairo/tests/src/instructions/test_memory_operations.cairo
- cairo/tests/src/instructions/test_memory_operations.py
- cairo/tests/src/instructions/test_push_operations.cairo
- cairo/tests/src/instructions/test_stop_and_math_operations.cairo
- cairo/tests/src/test_evm.cairo
- cairo/tests/utils/helpers.cairo
> feat: access initial state in the middle of a transaction

- cairo/ethereum/crypto/hash.cairo
- cairo/programs/os.cairo
- cairo/src/instructions/block_information.cairo
- cairo/src/model.cairo
- cairo/tests/programs/test_os.py
- cairo/tests/src/instructions/test_block_operations.cairo
- cairo/tests/src/instructions/test_block_operations.py
- cairo/tests/src/instructions/test_environmental_information.cairo
- cairo/tests/src/instructions/test_memory_operations.cairo
- cairo/tests/utils/helpers.cairo
> feat: implement 0x4a: blob_base_fee

- .github/workflows/python_tests.yml
- .gitignore
- cairo/tests/programs/test_os.py
- cairo/tests/src/utils/test_signature.py
- cairo/tests/utils/coverage.py
- pyproject.toml
- uv.lock
Also added `snakeviz` to be able to profile tests with `--profile`, for example
```
uv run pytest path/to/test_file.py --profile
```
and then use `snakeviz` to visualize the python tracing
> Simplify VMWithCoverage

- cairo/tests/conftest.py
Caching is implemented in a wrapper hook. This means it will run before regular hooks. 
To avoid compiling unnecessary cairo file, invoke `deselect_by_keyword` and `deselect_by_mark` before anything
> test: deselect by keyword and mark

- crates/exex/src/model/payload.rs
Ref https://github.com/kkrt-labs/keth/issues/182
Draft PR to check if this is in the intended direction.
Will correct the asserts to make sure the test passes
> feat: Add gen_arg test with arbitrary block 

- cairo/tests/fixtures/runner.py
- cairo/tests/utils/reporting.py
Speed up a bit the profiler by avoiding heavy useless ops, from 10+s to 0.7s for the test_erc20 (1.4M steps)
> Do not instantiate useless TracerData class

- cairo/ethereum/cancun/vm/memory.cairo
- cairo/ethereum_types/bytes.cairo
- cairo/pyproject.toml
- cairo/tests/ethereum/cancun/vm/test_memory.py
- cairo/tests/utils/args_gen.py
- cairo/tests/utils/serde.py
- uv.lock
> feat: EELS memory

- .cursorrules
- cairo/ethereum/cancun/state.cairo
- cairo/tests/test_serde.cairo
- cairo/tests/test_serde.py
- cairo/tests/utils/args_gen.py
- docs/code_architecture.md
Updates the cursorrules examples with better instructions, as the Stack example was an edge case where we had to make extra modifications.
adds transient storage type
> feat: transient storage type

- cairo/tests/ethereum/cancun/test_trie.py
- cairo/tests/ethereum/test_rlp.py
- cairo/tests/programs/test_os.py
- cairo/tests/src/instructions/test_environmental_information.py
- cairo/tests/src/precompiles/test_ripemd160.py
- cairo/tests/src/utils/test_signature.py
Part of #318 
For test > 2000s from https://github.com/kkrt-labs/keth/actions/runs/12526214515/job/34938536446, mark those test slow and set the max example to 300. 
At time of writing the max_examples for nightly is 1500 hence a division by 5 but still more than the main ci (which is 100)
> dev: limit examples for slow tests

- cairo/tests/conftest.py
- cairo/tests/utils/strategies.py
- pyproject.toml
- uv.lock
- in strategies.py, when an array of bytes is of fixed size, i.e. in `st.binary` `min_size == max_size`, then replace it by an integer of the correct size and map it to its bytes repr in little endian
closes #376
> dev: replace bytes strategies by integer of fixed size

- cairo/tests/conftest.py
- cairo/tests/ethereum/cancun/test_trie.py
- cairo/tests/ethereum/test_rlp.py
- cairo/tests/programs/test_os.py
- cairo/tests/src/instructions/test_environmental_information.py
- cairo/tests/src/precompiles/test_ec_recover.py
- cairo/tests/src/precompiles/test_ripemd160.py
- cairo/tests/src/precompiles/test_sha256.py
- cairo/tests/src/utils/test_signature.py
- cairo/tests/src/utils/test_transaction.py
Close #318
The nightly CI always fails due to being [too long](https://github.com/kkrt-labs/keth/issues/318#issuecomment-2574718661)
This PR reduce the number of examples and even more for specific very slow tests: the CI passes https://github.com/kkrt-labs/keth/actions/runs/12706365504
This could be review if self hosted runners are introduced
> test: reduce max examples nightly

- Cargo.lock
- Cargo.toml
- cairo/tests/ethereum/cancun/test_fork_types.py
- cairo/tests/ethereum/cancun/utils/test_address.py
- cairo/tests/ethereum/cancun/vm/instructions/test_arithmetic.py
- cairo/tests/ethereum/cancun/vm/instructions/test_bitwise.py
- cairo/tests/ethereum/cancun/vm/instructions/test_block.py
- cairo/tests/ethereum/cancun/vm/instructions/test_comparison.py
- cairo/tests/ethereum/cancun/vm/instructions/test_control_flow.py
- cairo/tests/ethereum/cancun/vm/instructions/test_keccak.py
- cairo/tests/ethereum/cancun/vm/instructions/test_log.py
- cairo/tests/ethereum/cancun/vm/instructions/test_memory_instructions.py
- cairo/tests/ethereum/cancun/vm/test_memory.py
- cairo/tests/ethereum/cancun/vm/test_runtime.py
- cairo/tests/ethereum/cancun/vm/test_stack.py
- cairo/tests/ethereum/crypto/test_hash.py
- cairo/tests/ethereum/test_rlp.py
- cairo/tests/src/test_stack.py
- cairo/tests/test_serde.py
- cairo/tests/utils/args_gen.py
- cairo/tests/utils/serde.py
- crates/cairo-addons/src/vm/dict_manager.rs
- crates/cairo-addons/src/vm/felt.rs
- crates/cairo-addons/src/vm/maybe_relocatable.rs
- crates/cairo-addons/src/vm/memory_segments.rs
- crates/cairo-addons/src/vm/relocatable.rs
- python/cairo-addons/tests/test_dict_manager.py
- python/cairo-addons/tests/test_memory_segments.py
improve rust bindings compat, enabling syntaxes like
- segments.memory.get(idx)
or 
- dict_trackers[idx] = X
based on a custom fork of the cairo vm in which I unbotherly created a special `DictKey` type which is an 
enum
```rust
#[derive(
Eq, Ord, Hash, PartialEq, PartialOrd, Clone, Debug,
)]
pub enum DictKey {
Simple(MaybeRelocatable),
Compound(Vec<MaybeRelocatable>),
}
```
Which allows a Vec of Felts / Relocatable to be used as dict keys. For us this is important because we need to track preimages that might not fit in a felt inside the dict tracker. 
This was implemented in a "dumb" way that is unconsidering of external side effects to the Cairo-VM - once synced with LC we will want to revisit the approach. see https://github.com/kkrt-labs/cairo-vm/tree/kkrt-compat
> feat: improve rust bindings compat

- cairo/ethereum/cancun/fork_types.cairo
- cairo/ethereum/cancun/state.cairo
- cairo/ethereum/cancun/trie.cairo
- cairo/src/utils/dict.cairo
- cairo/tests/ethereum/cancun/test_state.py
- cairo/tests/ethereum/cancun/test_trie.py
- cairo/tests/test_serde.py
- cairo/tests/utils/serde.py
- cairo/tests/utils/strategies.py
Setting to draft as tests cannot pass until we skip serialization of nested dictionaries that are filled with default_values in serde.py, as seen in https://github.com/ethereum/execution-specs/blob/master/src/ethereum/cancun/state.py#L318
closes #409
> feat: set storage

- cairo/ethereum/cancun/state.cairo
- cairo/tests/ethereum/cancun/test_state.py
> feat: is_account_alive

- cairo/ethereum/cancun/state.cairo
- cairo/tests/ethereum/cancun/test_state.py
- cairo/tests/utils/args_gen.py
- cairo/tests/utils/serde.py
- cairo/tests/utils/strategies.py
Closes #440 
Note: introduces a new field in the state that holds the original storage tries. 
Because in sstore, we get the original storage, meaning we need to access the snapshots[0] on each sstore. 
Because a dict_read writes memory data, it would mean we have to override snapshots[0] on each dict_read, which is inconvenient. 
This way, we can only overwrite the `original_storage_tries` field of the State struct.
> feat: get_storage_original

- cairo/tests/ethereum/cancun/vm/instructions/test_arithmetic.py
- cairo/tests/ethereum/cancun/vm/instructions/test_bitwise.py
- cairo/tests/ethereum/cancun/vm/instructions/test_block.py
- cairo/tests/ethereum/cancun/vm/instructions/test_comparison.py
- cairo/tests/ethereum/cancun/vm/instructions/test_control_flow.py
- cairo/tests/ethereum/cancun/vm/instructions/test_keccak.py
- cairo/tests/ethereum/cancun/vm/instructions/test_log.py
- cairo/tests/ethereum/cancun/vm/instructions/test_memory_instructions.py
- cairo/tests/ethereum/cancun/vm/instructions/test_stack_instructions.py
- cairo/tests/ethereum/cancun/vm/instructions/test_storage.py
- cairo/tests/ethereum/cancun/vm/test_gas.py
- cairo/tests/utils/errors.py
Closes #438
use a special contextmanager that asserts the error raised is EXACTLY of the expected type.
> tests: stricter error assertions

- cairo/ethereum/cancun/vm.cairo
- cairo/ethereum/cancun/vm/instructions/storage.cairo
- cairo/tests/ethereum/cancun/vm/instructions/test_storage.py
- cairo/tests/fixtures/runner.py
> feat: sstore

- cairo/ethereum/cancun/state.cairo
- cairo/tests/ethereum/cancun/test_state.py
> feat: increment nonce

- cairo/ethereum/cancun/state.cairo
- cairo/tests/ethereum/cancun/test_state.py
> feat: touch account

- cairo/ethereum/cancun/vm/instructions/stack_instructions.cairo
- cairo/tests/ethereum/cancun/vm/instructions/test_stack_instructions.py
> feat: pop instructions

- cairo/ethereum/cancun/vm/instructions/environment.cairo
- cairo/ethereum/utils/numeric.cairo
- cairo/tests/ethereum/cancun/vm/instructions/test_environment.py
- cairo/tests/ethereum/utils/test_numeric.py
- cairo/tests/utils/evm_builder.py
- cairo/tests/utils/strategies.py
> feat: environment instructions

- cairo/ethereum/cancun/vm/instructions/environment.cairo
- cairo/ethereum/utils/numeric.cairo
- cairo/tests/ethereum/cancun/vm/instructions/test_environment.py
> feat: blob_hash

- cairo/ethereum/cancun/vm/instructions/environment.cairo
- cairo/tests/ethereum/cancun/vm/instructions/test_environment.py
- cairo/tests/utils/evm_builder.py
> feat: returndatacopy

- cairo/ethereum/cancun/vm/instructions/storage.cairo
Close #510 
Should match EELS
https://github.com/ethereum/execution-specs/blob/master/src/ethereum/cancun/vm/instructions/storage.py#L94-L100
```
if original_value == current_value and current_value != new_value:
if original_value == 0:
gas_cost += GAS_STORAGE_SET
else:
gas_cost += GAS_STORAGE_UPDATE - GAS_COLD_SLOAD
else:
gas_cost += GAS_WARM_ACCESS
```
> fix: sstore

- cairo/ethereum/cancun/state.cairo
- cairo/tests/utils/args_gen.py
- cairo/tests/utils/serde.py
adapts args_gen and serde to re-construct the python types from this new layout.
removes snapshot building in *_transaction functions
(+ fixes bug detected in nightly)
Closes https://github.com/kkrt-labs/keth/issues/515
> dev: remove snapshots in internal state types

- cairo/ethereum/cancun/vm/interpreter.cairo
- cairo/tests/ethereum/cancun/vm/test_interpreter.py
- cairo/tests/utils/strategies.py
> feat: process_create_message

- cairo/ethereum/cancun/state.cairo
- cairo/tests/ethereum/cancun/test_state.py
- cairo/tests/utils/args_gen.py
- crates/cairo-addons/src/vm/dict_manager.rs
- python/cairo-addons/src/cairo_addons/hints/dict.py
Closes https://github.com/kkrt-labs/keth/issues/533
> fix: handling of dict relationships in args gen

- cairo/ethereum/cancun/vm/interpreter.cairo
- cairo/tests/ethereum/cancun/vm/test_interpreter.py
- cairo/tests/utils/message_builder.py
see:
> edit: actually BEFORE calling process_message_create we ensure that the message depth is < STACK_DEPTH_LIMIT, so you can disregard my message. I think the following case is just never triggered and the assertion is never triggered
> I also have an unresolved question about what happens when doing a CREATE opcode that hits the message stack limit:
> Let's say i'm executing a simple CREATE opcode, starting from process_message
> `process_message(begin_transaction:1) -> execute_code -> CREATE -> generic_create -> process_create_message (begin_transaction: 2) -> process_message❌ fails because stack too deep
> This error is caught in the execute_code, which fills the evm.error, then returns to process_message in which we rollback_transaction, which brings our amount of snapshots back to …
> dev: remove useless assertion on stack depth in process_message

- cairo/ethereum/cancun/vm.cairo
- cairo/ethereum/cancun/vm/gas.cairo
- cairo/ethereum/cancun/vm/instructions.cairo
- cairo/ethereum/cancun/vm/instructions/system.cairo
- cairo/ethereum/cancun/vm/interpreter.cairo
- cairo/tests/ethereum/cancun/vm/instructions/test_system_cairo.cairo
- cairo/tests/ethereum/cancun/vm/instructions/test_system_cairo.py
- cairo/tests/ethereum/cancun/vm/test_instructions.cairo
- cairo/tests/ethereum/cancun/vm/test_instructions.py
> feat: generic create

- cairo/tests/ethereum/cancun/vm/instructions/test_environment.py
- cairo/tests/utils/evm_builder.py
- cairo/tests/utils/strategies.py
We had an issue in the way we were generating strategies. 
Closes #581 
> 
> ## Description
> When using Hypothesis with nested dataclasses containing mutable objects (like dictionaries), mutations to these objects can persist between test runs, leading to unexpected state and potential test failures.
> 
> ## Minimal Reproducible Example
> 
> ```
> from hypothesis import strategies as st
> @dataclass
> class InnerDicts:
>     field0: Dict[int, int]
>     field1: Dict[int, Dict[bytes, bytes]]
> 
> empty_inner_dicts = st.builds(InnerDicts, field0=st.just({}), field1=st.just({}))
> 
> @dataclass
> class OuterClass:
>     state: InnerDicts
>     field1: int
>     field2: int
> 
> outer_class_strategy = st.builds(OuterClass, state=empty_inner_dicts, field1=st.integers(), field2=st.integers()) …
```
> fix: mutable object strategy generation

- cairo/ethereum/cancun/fork.cairo
- cairo/ethereum/cancun/transactions.cairo
- cairo/ethereum/cancun/transactions_types.cairo
- cairo/ethereum/cancun/trie.cairo
- cairo/ethereum/cancun/vm.cairo
- cairo/ethereum/cancun/vm/gas.cairo
- cairo/ethereum/cancun/vm/instructions/system.cairo
- cairo/ethereum_rlp/rlp.cairo
- cairo/tests/ethereum/cancun/test_fork.py
- cairo/tests/ethereum/cancun/test_transactions.py
- cairo/tests/test_serde.cairo
- cairo/tests/utils/args_gen.py
Closes https://github.com/kkrt-labs/keth/issues/546
Creates transactions_types file to avoid circular imports.
Also move the calculate_intrinsic_cost to transaction.py for the same reason (and to match EELS).
> feat: validate transaction

- cairo/ethereum/cancun/transactions.cairo
- cairo/ethereum_rlp/rlp.cairo
- cairo/tests/ethereum/cancun/test_transactions.py
- cairo/tests/ethereum_rlp/test_rlp.py
- uv.lock
closes #588 
- added encode utils specifically for signing utils, didn't modify the existing encode utils as they will be used in [`apply_body`](https://github.com/ethereum/execution-specs/blob/d9febcb7332d62194968dcdb7775adf497c93626/src/ethereum/paris/fork.py#L487)
- added tests
- added utils for signing hash
> feat: signing hash utils

- cairo/ethereum/cancun/vm/precompiled_contracts/identity.cairo
- cairo/ethereum/cancun/vm/precompiled_contracts/mapping.cairo
- cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_identity.py
- cairo/tests/ethereum/cancun/vm/test_interpreter.py
> feat: identity precompile

- cairo/ethereum/cancun/vm/instructions.cairo
- cairo/ethereum/cancun/vm/instructions/comparison.cairo
- cairo/ethereum/cancun/vm/interpreter.cairo
- cairo/tests/ethereum/cancun/vm/instructions/test_comparison.py
the jumptable was calling the is_zero cairo instead of the is_zero opcode.
> fix: is_zero opcode

- cairo/ethereum/cancun/fork.cairo
- cairo/ethereum/cancun/utils/message.cairo
- cairo/ethereum/cancun/vm/gas.cairo
- cairo/ethereum/cancun/vm/interpreter.cairo
- cairo/ethereum/utils/numeric.cairo
- cairo/tests/ethereum/cancun/test_fork.py
- cairo/tests/ethereum/cancun/vm/test_gas.py
- cairo/tests/ethereum/utils/test_numeric.py
- python/cairo-addons/src/cairo_addons/hints/dict.py
- python/cairo-addons/src/cairo_addons/hints/hashdict.py
- fixes the strategy of process_transaction to only generate valid gas values regarding basefee
- fixes the preaccessed addresses & keys to be instanciated with a default dict with default 0
- fixes the state used in reads post-execution to be the updated on from the env
- saturate blob gas / gas price values to 2**64
- stop early taylor exponentiation when accumulated numerator is > 2**128
- limit excess_blob_gas to 10*target in strategy, to avoid the pythonic taylor exponentiation to run forever.
- fix the assertions made in `process_transaction` to handle raises AND exceptions in return values
> fix: process-transaction src & strategy

- cairo/tests/utils/args_gen.py
> fix: environment patched import fails in EELS as it has no `traces` field

- python/cairo-addons/src/cairo_addons/testing/coverage.py
le logger de perf de coverage rend la nightly trop verbose
je recommande de supprimer les log info dans le coverage
> dev: remove logging perf of coverage in main

- cairo/ethereum/cancun/fork.cairo
- cairo/tests/ethereum/cancun/test_fork.py
Closes #652 
Strategies ported from https://github.com/kkrt-labs/keth/pull/653
> fix: test_process_transaction

- python/cairo-addons/src/cairo_addons/testing/fixtures.py
Running with `-s` will print the misses for the current file. The IDE lets you then click to the line
> Print miss for current file

- python/cairo-ec/src/cairo_ec/ec_ops.cairo
- python/cairo-ec/tests/test_ec_ops.cairo
- python/cairo-ec/tests/test_ec_ops.py
Closes #707 
I've added 2 test cases to cover the checks of `ec_add` when Q = P and Q = -P
> refactor: use ec_add & ec_double from compiled circuits

- cairo/ethereum/cancun/state.cairo
- cairo/ethereum/cancun/transactions.cairo
- cairo/ethereum/cancun/transactions_types.cairo
- cairo/ethereum/cancun/trie.cairo
- cairo/ethereum/cancun/utils/address.cairo
- cairo/ethereum_rlp/rlp.cairo
> use ret instead of 0 return

- cairo/ethereum/cancun/trie.cairo
- cairo/tests/ethereum/cancun/test_trie.py
> start fixing cov for trie

- cairo/ethereum/cancun/fork.cairo
- cairo/ethereum/cancun/transactions.cairo
- cairo/ethereum/cancun/transactions_types.cairo
- cairo/tests/ethereum/cancun/test_transactions_types.py
> cov tx utils

- python/cairo-core/src/cairo_core/maths.cairo
- python/cairo-core/tests/src/cairo_core/test_maths.py
The summation check in the function is necessary (and even quite clever) to verify that if you weight the provided “digits” (or bytes) by the base powers and add them up you get back the original value (or its lower bits). However, **this check by itself is not sufficient to guarantee that the output is the _canonical_ byte‐decomposition of the input**. Here’s why:
1. **Lack of Per‐Digit Range Enforcement:**  
The reconstruction only checks that
$$
\[
\text{acc} = \sum_{i=0}^{\text{len}-1} (\text{output}[i] \times 256^i)
\]
$$
equals either the original value (if `len == 31`) or the value “masked” to the lower $\(256^{\text{len}}\)$ bits. This equality would be satisfied by many different choices of the `output` array if there were no constraints on an individual element. In a unique …
> fix soundness in to_bytes

- cairo/ethereum/cancun/trie.cairo
- cairo/tests/ethereum/cancun/test_trie.py
- cairo/tests/utils/args_gen.py
- cairo/tests/utils/strategies.py
- python/cairo-addons/src/cairo_addons/hints/hashdict.py
Closes #636 
note: this is using the storage_tries as Trie[Bytes32, U256]. At some point we will need to re-build this trie in Cairo from the Trie[Tuple[Address, Bytes32], U256].
We need to scope an issue on how to go from our internal representation to a storage trie per account. This likely goes in the state root epic
> feat: _prepare_trie

- cairo/ethereum/cancun/vm/instructions/storage.cairo
- cairo/tests/ethereum/cancun/vm/instructions/test_storage.py
UPDATE: bug fixed in [f93f2d9](https://github.com/kkrt-labs/keth/pull/756/commits/f93f2d91ac2c89f0bbfa5a62d6e2ece9147ec3ee)
closes #757
> bug: failing test on sload

- cairo/ethereum/cancun/trie.cairo
- python/cairo-addons/src/cairo_addons/hints/hashdict.py
The problem is that `if value` would return `False` if `value := 0`. But if we delete the entry in a trie (by writing 0), then the next read on the same (address, key) should be returning `0` as `prev_value`, not `default_factory()`. This caused an issue when squashing the storage_tries when computing the storage roots.
> fix: hashdict_read hint should not skip zero values

- Cargo.lock
- Cargo.toml
- cairo/tests/ethereum/cancun/test_trie.py
- cairo/tests/ethereum/cancun/vm/precompiled_contracts/test_mapping.py
- cairo/tests/legacy/utils/test_bytes_legacy.py
- cairo/tests/utils/args_gen.py
- crates/cairo-addons/src/vm/dict_manager.rs
- crates/cairo-addons/src/vm/felt.rs
- crates/cairo-addons/src/vm/hint_definitions/hashdict.rs
- crates/cairo-addons/src/vm/maybe_relocatable.rs
- python/cairo-addons/src/cairo_addons/hints/dict.py
- python/cairo-addons/src/cairo_addons/hints/hashdict.py
- python/cairo-addons/src/cairo_addons/testing/fixtures.py
- python/cairo-core/tests/src/cairo_core/test_maths.py
- python/cairo-ec/tests/circuits/test_circuits.py
> feat: use DictManager's `preimage` field to track preimages of hashed keys

- cairo/tests/ethereum/cancun/test_trie.py
**Description**
This pull request updates the `test_get_branch_for_nibble_at_level` function in `test_trie.py` to improve the handling of the branch variable. 
**The changes include:**
- Removed redundant assignment of the branch variable.
- Streamlined the assertion logic to ensure that the expected output matches the actual output from the obj dictionary.
These modifications enhance the clarity and efficiency of the test, ensuring it accurately verifies the functionality of the nibble list conversion.
> Fix Test Function for Nibble List Conversion

- cairo/ethereum_rlp/rlp.cairo
Fixes an off-by-one error in decode_to_bytes - and wraps the assertions with the proper DecodingError error.
> fix: off-by-one error in decode_to_bytes

- crates/cairo-addons/src/vm/hint_utils/mod.rs
> fix: serialize sequence hint

- cairo/ethereum/cancun/vm/instructions/environment.cairo
missing stack rebind on returndatacopy upon early return.
> fix: missing stack rebind returndatacopy

- cairo/ethereum/cancun/vm/instructions/block.cairo
> fix: U256 block_hash construction

- cairo/ethereum/cancun/state.cairo
- crates/cairo-addons/src/vm/hint_definitions/hashdict.rs
- python/cairo-addons/src/cairo_addons/hints/hashdict.py
This is a rough patch of this issue by adding another hint that filtrates for zero values. This is not the definitive design, which will be refactored to handle proofs of non-inclusion.
This is the same as get_keys_for_address_prefix, only we do not collect zero-values.
Closes #924
> fix: account_has_storage in cases of destroyed storage

- python/cairo-addons/src/cairo_addons/profiler.py
Optimization strategies:
- Leverage the Polars Lazy API to avoid running computations on intermediate dataframes
- Considerably reduce the size of the trace [fp, pc] used, only keeping one pc per fp
Results:
- No more crashes on 20GB+ crashes
- A lot faster (20s for 800M steps trace)
Sides:
- Documented the process
> dev: optimize profiler

- .gitignore
- Cargo.lock
- Cargo.toml
- cairo/tests/ethereum/cancun/vm/test_runtime.cairo
- cairo/tests/legacy/utils/test_array.cairo
- cairo/tests/legacy/utils/test_array.py
- cairo/tests/legacy/utils/test_bytes_legacy.cairo
- cairo/tests/legacy/utils/test_bytes_legacy.py
- cairo/tests/legacy/utils/test_utils.cairo
- crates/cairo-addons/Cargo.toml
- crates/cairo-addons/src/vm/program.rs
- crates/cairo-addons/src/vm/runner.rs
- python/cairo-addons/src/cairo_addons/testing/runner.py
- python/cairo-addons/tests/test_runner.py
Closes https://github.com/kkrt-labs/keth/issues/952
Closes #960
This pull request further pushed the functional parity between the Rust-based Cairo VM runner (`PyCairoRunner`) and the existing Python VM runner (`run_python_vm`) by adding support for **Proof Mode**.
Key changes include a refactored `runner.py` file with an 8-step structure, mirrored in both vm runs, extended Rust bindings in `runner.rs`. 
1. **Refactored `run_rust_vm` in `runner.py`**
- **Objective**: Mirror the 8-step structure of `run_python_vm` for consistency and maintainability.
- **Details**:
- **Step 1**: Program selection and entrypoint metadata extraction using `build_entrypoint`.
- **Step 2**: Runner initialization with `RustCairoRunner`, supporting proof mode and layout configuration.
- **Step 3**: Stack …
> feat: enable proof mode in Rust

- .github/workflows/nightly_fuzzing.yml
- .github/workflows/python_tests.yml
- cairo/ethereum/cancun/vm/interpreter.cairo
- cairo/tests/test_hint_runner.cairo
- cairo/tests/test_hint_runner.py
- crates/cairo-addons/src/vm/dict_manager.rs
- crates/cairo-addons/src/vm/memory_segments.rs
- crates/cairo-addons/src/vm/pythonic_hint.rs
- crates/cairo-addons/src/vm/runner.rs
- crates/cairo-addons/src/vm/vm_consts.rs
- dictionary.txt
- python/cairo-addons/src/cairo_addons/hints/injected.py
- python/cairo-addons/src/cairo_addons/testing/hooks.py
- python/cairo-addons/src/cairo_addons/testing/runner.py
Closes https://github.com/kkrt-labs/keth/issues/908
Closes #961 
Closes #964
This PR significantly improves the interaction between Cairo variables and Python hints by enhancing the variable access system in the Rust VM. It adds comprehensive test cases and implements several key features to make Python hints more powerful and intuitive.
- **Variable Access Improvements**: Added support for accessing `ap`, `pc`, and `fp` directly in Python hints
- **Memory Management**: Implemented `__setitem__` in `PyMemoryWrapper` to allow setting memory values
- **Variable Assignment**: Added ability to assign values to unassigned Cairo variables from Python hints
- **Struct Member Access**: Enhanced support for accessing struct members and nested structs
- **Pointer Dereferencing**: Improved pointer …
> feat: enhance pythonic hints

- python/cairo-ec/src/cairo_ec/curve/g1_point.cairo
- python/cairo-ec/src/cairo_ec/curve/g1g2pair.cairo
- python/cairo-ec/src/cairo_ec/curve/g2_point.cairo
Closes #973 
Add the basic structs `G2Point` and `G1G2Pair` to be used for pairings.
They will be used whether we compute the pairings, or implement the multi pairing checks
> feat: base structs for pairings

- .github/workflows/nightly_fuzzing.yml
- .github/workflows/python_tests.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- README.md
- cairo/ethereum/cancun/fork.cairo
- cairo/ethereum/cancun/main.cairo
- cairo/ethereum/cancun/vm/interpreter.cairo
- cairo/scripts/compile_cairo.py
- cairo/scripts/prove_block.py
- cairo/scripts/zkpi_to_eels.py
- cairo/tests/test_hint_runner.py
- crates/cairo-addons/Cargo.toml
- crates/cairo-addons/README.md
- crates/cairo-addons/src/vm/hints.rs
- crates/cairo-addons/src/vm/mod.rs
- crates/cairo-addons/src/vm/pythonic_hint.rs
- crates/cairo-addons/src/vm/runner.rs
- crates/cairo-addons/src/vm/vm_consts.rs
- dictionary.txt
- pyproject.toml
- python/cairo-addons/pyproject.toml
- python/cairo-addons/src/cairo_addons/hints/injected.py
- python/cairo-addons/src/cairo_addons/testing/hooks.py
- python/cairo-addons/src/cairo_addons/testing/runner.py
- rust-toolchain
- uv.lock
Closes #959  
Closes #968  
Closes #975 
Closes #1006
**Title:** Optimize Rust Runner for Proof Mode and Integrate Stwo Proof Generation
**Issues Addressed:**
1. Update Rust runner to minimize performance impact of pythonic hints in proof mode.
2. Add script to prove Ethereum blocks using Cairo runner with ZKPI inputs.
3. Integrate Stwo proof generation into the `run-block` pipeline, bypassing intermediate trace files.
**Changes:**
- **Rust Runner Optimization:**
- Removed `pythonic-hints` feature flag; hints always supported.
- Added `enable_traces` flag to control logger hint execution (skipped by default for performance).
- Skipped `logger.trace` hints unless `enable_traces` is true.
- Mapped hint IDs to functions directly on top of mapping of Python code to hint functions.
- Updated …
> feat: e2e Keth block proving

- cairo/ethereum/crypto/alt_bn128.cairo
- cairo/tests/ethereum/crypto/test_alt_bn128.py
Closes #995 
Implements the addition between two BNF12 elements.
Test based on the existing bnf12 strategy
~~It also introduces a fixture and a function to generate random BNF12 elements, for testing purposes.~~
Edit: The current struct BNF12 has coefficients as u256, thus it requires casting all coefficients to u384 to use mod_ops circuits, then back to u256 ; The choice of u256 was for cell efficiency, but if we have to do 12*2 casts, it might actually be worse --> might need to refactor this design choice before merging
Wait for #1022 to be merged to remove cast
> feat: implement bnf12 addition

- cairo/ethereum/crypto/alt_bn128.cairo
- cairo/tests/ethereum/crypto/test_alt_bn128.py
Closes #997 
It also reorders `bnf12_sub` which was declared after the `BNP12` struct
> feat: implement bnf12_scalar_mul

- cairo/ethereum/crypto/alt_bn128.cairo
- cairo/tests/ethereum/crypto/test_alt_bn128.py
- cairo/tests/test_serde.py
- cairo/tests/utils/args_gen.py
- cairo/tests/utils/serde.py
- cairo/tests/utils/strategies.py
Closes #1045
Closes #1050 
Closes #1046
~~`BNP` is an alias of G1Point, which is specifically used in the context of the alt_bn128 curve~~
--> Goal is to have a function which takes x,y coordinates, verifies that the resulting point is on the alt_bn128 curve, and returns it
> feat: add BNP init

- .github/actions/setup-environment/action.yaml
- .github/workflows/nightly_fuzzing.yml
- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- .github/workflows/python_tests.yml
- .trunk/configs/.yamllint.yaml
- cairo/scripts/prove_block.py
- cairo/scripts/zkpi_to_eels.py
- python/mpt/src/mpt/ethereum_tries.py
Caches rust builds so that the cairo-addons crate built under `./target` with `maturin` is cached
```
DEBUG     Finished `release` profile [optimized] target(s) in 3m 42s
DEBUG 📦 Built wheel for abi3 Python ≥ 3.9 to /Users/msaug/kkrt-labs/keth/target/wheels/cairo_addons-0.1.0-cp39-abi3-macosx_11_0_arm64.whl
DEBUG /Users/msaug/kkrt-labs/keth/target/wheels/cairo_addons-0.1.0-cp39-abi3-macosx_11_0_arm64.whl
DEBUG Finished building: cairo-addons @ file:///Users/msaug/kkrt-labs/keth/python/cairo-addons
Built cairo-addons @ file:///Users/msaug/kkrt-labs/keth/python/cairo-addons
```
Normally it's built under ./target/wheels
> ci: add rust caching to test jobs

- crates/cairo-addons/src/vm/hint_definitions/maths.rs
`value_len_mod_two` was present in the list twice
> chore: remove duplicated list entry

- python/mpt/src/mpt/trie_diff.cairo
- python/mpt/src/mpt/trie_diff.py
This PR addresses a bug in the `_compute_diff` function within `trie_diff.cairo`, specifically related to the comparison of `LeafNode` and `ExtensionNode` types.
**Key Improvements:**
* **Prefix-Based Key Segment Handling:**
* The code now employs `Bytes__startswith__` to verify if an `ExtensionNode`'s key segment is a prefix of a `LeafNode`'s remaining key.
* This ensures accurate key segment subtraction when comparing nodes.
* **Handling Non-Prefix Scenarios:**
* When the `ExtensionNode`'s key segment is *not* a prefix of the `LeafNode`'s key, the PR correctly identifies this as a deletion of the extension subtree and a creation of the leaf.
* The code now correctly recurses down the deleted extension subtree.
* The code now correctly logs the creation of the new leaf node.
* **Accurate …
> fix: add leaf extension edge case

- .github/workflows/pull_request.yml
- .github/workflows/python_tests.yml
- python/cairo-addons/src/cairo_addons/testing/coverage.py
- python/cairo-addons/src/cairo_addons/testing/fixtures.py
- python/cairo-addons/src/cairo_addons/testing/runner.py
Closes #1153
**Context:**
Running tests in CI with high parallelism (e.g., -n 40 or more) was leading to excessive memory consumption per worker, often causing crashes due to Out-Of-Memory errors. Initial investigation suspected that the handling of coverage data was inefficient.
**Investigation & Problem:**
Analysis confirmed that the primary cause was the `coverage` pytest fixture (`fixtures.py`). Its original implementation worked as follows:
1.  For each test function executed within a test module (`test_*.py`), it calculated a coverage report (a Polars DataFrame).
2.  It appended *each* of these DataFrames to an in-memory list (`reports`).
3.  After all tests in the module finished, it concatenated *all* collected DataFrames (`pl.concat(reports)`) and performed aggregation.
This …
> dev: dump coverage data as parquet file to optimize memory usage.

- Cargo.lock
- Cargo.toml
- cairo/tests/test_hint_runner.cairo
- cairo/tests/test_hint_runner.py
- crates/cairo-addons/src/vm/hints.rs
- crates/cairo-addons/src/vm/pythonic_hint.rs
- crates/cairo-addons/src/vm/vm_consts.rs
Closes #1191
Uses the newly added hint data in the cairo vm to resolve the imported constants ("alias") and the local constant, making them available in the `ids` object.
> feat: support accessing scope constants in rust hints

- .vscode/settings.json
- cairo/tests/ethereum/crypto/test_alt_bn128.py
- crates/cairo-addons/src/vm/memory_segments.rs
- crates/cairo-addons/src/vm/mod.rs
- crates/cairo-addons/src/vm/mod_builtin_runner.rs
- crates/cairo-addons/src/vm/pythonic_hint.rs
- crates/cairo-addons/src/vm/relocatable.rs
- crates/cairo-addons/src/vm/runner.rs
- pyproject.toml
- uv.lock
- **VSCode Settings**: Added `cairols.venvCommand` and expanded `cairols.cairoPath` to include multiple Python source dirs, required for the LS to work with Garaga
- **Test Updates**: Replaced `cairo_run_py` with `cairo_run` in `test_alt_bn128.py`, using the RustVM instead of PythoNVM. Removed outdated performance comments and adjusted test settings (e.g., dropped `max_examples=1`).
- **Memory Management**: Refactored `PyMemorySegmentManager` and `PyMemoryWrapper` in `memory_segments.rs` to use raw pointers to `MemorySegmentManager` and `Memory` directly, bypassing `VirtualMachine`. Added a custom `memory_get` helper to handle relocatable/integer retrieval until upstream PR on cairo-vm merges.
- **ModBuiltinRunner**: Introduced `mod_builtin_runner.rs` with Python bindings for …
> feat: enable garaga hints through RustVM

- .github/actions/setup-environment/action.yaml
- .github/workflows/rust_tests.yml
As per https://github.com/Swatinem/rust-cache the `shared-key` option overrides the default job-based key, so that rust caches can be reused among jobs. This should significantly reduce the size of rust caches, which should be divided by 3 (ef-tests, python_unit, rust_unit)
> ci: use shared rust-cache key

- crates/cairo-addons/src/vm/hint_definitions/utils.rs
Closes #1295 
New flamegraph: (jumpdest_check_push_last_32_bytes has now approx. ~0.01% of total samples of the program (same block)
```
(master) $ cargo clean; uv run --reinstall compile_keth; time uv run prove-block 22223972
uv run prove-block 22223972  **63.86s user 19.82s system 90% cpu 1:32.89 total**
(feat/simplify_jumpdest_check_push_last_32_bytes) $ cargo clean; uv run --reinstall compile_keth; time uv run prove-block 22223972
uv run prove-block 22223972  **60.70s user 19.12s system 89% cpu 1:28.81 total**
```
> feat: Improve jumpdest_check_push_last_32_bytes rust hint

- codecov.yml
closes #1198 
strategy choice (very lean strategy, can be improved later):
- allow for slight decrease in coverage for ethereum_rlp package (indirect decrease) as I've noticed that over the last 5 PRs, the CI fails from an indirect decrease in coverage of ethereum_rlp package due to fuzzing framework being random
> dev: allow small decrease in coverage on ethereum_rlp

- cairo/ethereum/utils/bytes.cairo
- cairo/tests/ethereum/utils/test_bytes.py
- python/cairo-addons/src/cairo_addons/testing/errors.py
Empirically, this decreases the step usage of this function of ~30% (4.3M -> 3.3M) on sample block 22188088, from 520 to 400 per-call.
Closes #1316
> dev: optimize Bytes__eq__

- cairo/ethereum/cancun/vm/instructions/system.cairo
Closes https://github.com/kkrt-labs/keth/issues/1319
The issue was that we were calling `get_account_code`, mutating the `state`, but not properly re-binding the `state` to the `environment`.  Shifting the lines orders fixes that.
> fix: state rebinding issue after get_account_code

- .github/workflows/pull_request.yml
reduces to 48 workers on ef-test job, as we're hitting RAM usage limits, causing sigkill of the job
> ci: reduce n workers in ef-test to avoid OOM sigkill

- Cargo.lock
- Cargo.toml
- cairo/ethereum/cancun/bloom.cairo
- cairo/ethereum/cancun/fork.cairo
- cairo/ethereum/cancun/state.cairo
- cairo/ethereum/cancun/trie.cairo
- cairo/ethereum/cancun/vm/interpreter.cairo
- cairo/ethereum/cancun/vm/precompiled_contracts/ripemd160.cairo
- cairo/ethereum/crypto/alt_bn128.cairo
- cairo/ethereum/crypto/bls12_381.cairo
- cairo/legacy/utils/dict.cairo
- cairo/tests/ef_tests/helpers/load_state_tests.py
- cairo/tests/ethereum/cancun/test_fork.py
- cairo/tests/ethereum/cancun/test_main.py
- cairo/tests/legacy/utils/test_dict.cairo
- crates/cairo-addons/src/vm/dict_manager.rs
- crates/cairo-addons/src/vm/hint_definitions/dict.rs
- crates/cairo-addons/src/vm/hint_definitions/hashdict.rs
- crates/cairo-addons/src/vm/runner.rs
- dictionary.txt
- docs/AI-REPORT.md
- python/cairo-addons/src/cairo_addons/testing/runner.py
- python/mpt/src/mpt/trie_diff.cairo
Finally closes #535
**Dict Squashing Soundness**: To ensure all dictionaries are properly squashed
during block proving, we've implemented a verification mechanism in our CairoVM
runner.
- **Debugging Process**: Added `attach_name` hints in Cairo code to label
dictionaries, aiding in tracking and debugging squashing status. e.g:
attaching the name 'transactions' to the dict for the transactions trie:
```cairo
let (transaction_ptr) = default_dict_new(0);
tempvar dict_ptr = transaction_ptr;
tempvar name = 'transactions';
%{ attach_name %}
```
- **Verification Logic**: In the CairoVM repo, `DictTracker` now includes
`is_squashed` (initialized `True`) and `name` fields (to make debugging
easier). Mutations (`get_value`, `insert_value`) set `is_squashed` to `False`,
and we modified our …
> dev: added checks for unsquashed dicts in runner

- .github/workflows/dependencies.yml
This PR updates the astral-sh/setup-uv action from v3 to v5 in dependencies.yml to align with the version used in action.yaml.
Using a consistent version ensures compatibility and stability across workflows.
Reference: [Official Astral docs – GitHub integration guide](https://docs.astral.sh/uv/guides/integration/github/)
> ci: update setup-uv action to v5 in dependencies.yml

- cairo/ethereum/cancun/fork.cairo
- cairo/ethereum/cancun/state.cairo
- cairo/ethereum/cancun/vm/interpreter.cairo
- cairo/legacy/utils/dict.cairo
- cairo/tests/ethereum/cancun/test_state.py
- cairo/tests/legacy/utils/test_dict.cairo
- cairo/tests/legacy/utils/test_dict.py
- crates/cairo-addons/src/vm/hint_definitions/dict.rs
- crates/cairo-addons/src/vm/hint_definitions/hashdict.rs
- python/cairo-addons/src/cairo_addons/hints/dict.py
- python/cairo-addons/src/cairo_addons/hints/hashdict.py
- python/keth-types/src/keth_types/patches.py
- python/keth-types/src/keth_types/types.py
- python/mpt/src/mpt/trie_diff.cairo
- python/mpt/src/mpt/types.cairo
Closes https://github.com/kkrt-labs/keth/issues/1108
Closes https://github.com/kkrt-labs/keth/issues/1382 (necessary fix in this pr)
Several things addressed in this PR. The main goal is to fix the way we handle deleted account, which currently is unsound. I started by identifying all such cases where we might encounter these cases of deletions. One thing to be careful about are rules remnant from outdated EVM forks, and the blocks >= Cancun we're going to prove. 
**Note:** It has been confirmed that, Post-Merge, there exists no account in the ethereum state that is empty but has storage.
As per [EIP-161](https://eips.ethereum.org/EIPS/eip-161)
>  Notes
> In the present Ethereum protocol, it should be noted that very few state changes can ultimately result in accounts that are empty …
> fix: handle deleted accounts in a sound way

- python/cairo-addons/src/cairo_addons/testing/runner.py
generate empty segments (useful for keccak_ptr: felt* or blake2s_ptr: felt*) when running `cairo_run`
> dev: support auto-generation of empty segments in runner

- .github/workflows/pull_request.yml
- .trunk/configs/.markdownlint.yaml
- cairo/ethereum/cancun/fork.cairo
- cairo/ethereum/cancun/fork_types.cairo
- cairo/ethereum/cancun/main.cairo
- cairo/ethereum/cancun/state.cairo
- cairo/ethereum/cancun/trie.cairo
- cairo/ethereum/crypto/hash.cairo
- cairo/ethereum_rlp/rlp.cairo
- cairo/legacy/utils/bytes.cairo
- cairo/tests/ethereum/cancun/test_fork.py
- cairo/tests/ethereum/cancun/test_state.py
- cairo/tests/ethereum/cancun/test_trie.py
- cairo/tests/ethereum/crypto/test_hash.py
- cairo/tests/legacy/utils/test_bytes_legacy.cairo
- cairo/tests/legacy/utils/test_bytes_legacy.py
- cairo/tests/utils/args_gen.py
- cairo/tests/utils/strategies.py
- crates/cairo-addons/src/vm/hint_definitions/bytes_hints.rs
- docs/AI-REPORT.md
- python/cairo-addons/src/cairo_addons/testing/runner.py
- python/cairo-core/src/cairo_core/hash/blake2s.cairo
**Closes #1389**
This PR reverts the diff-based state validation (AI-Report April 11, 2025) to restore `state_root` and `storage_root` computation in Keth, introducing hash function abstraction for Keccak, Blake2s, and future Poseidon support.
- **State Root Restoration (`state.cairo`)**: Reintroduced `state_root` and added `storage_roots` with helpers to compute MPT roots, squashing tries for unique keys.
- **Hash Abstraction**:
- Updated `state_root`, `storage_roots`, `root` (`trie.cairo`), and related functions to include implicit hash builtins (`keccak_ptr`, `poseidon_ptr`), and `hash_function_name: felt`.
- Added `hash_with` (`hash.cairo`) to dispatch to Keccak or Blake2s based on `hash_function_name`, replacing hardcoded `keccak256`.
- Implemented `blake2s_bytes` and …
> feat: restore state root computation & abstract hash functions used

- .github/actions/setup-environment/action.yaml
- .github/workflows/dependencies.yml
v6 halves install time, adds first-class dependency caching, and removes options deprecated in v5 that will break once runners drop legacy support. Upgrading keeps CI fast and future-proof
> ci: bump astral-sh/setup-uv action to v6

- cairo/tests/ethereum/cancun/keth/test_e2e.py
- cairo/tests/ethereum/cancun/keth/test_teardown.py
- cairo/utils/fixture_loader.py
- docs/AI-REPORT.md
- python/keth-types/src/keth_types/types.py
- python/mpt/src/mpt/ethereum_tries.py
- python/mpt/src/mpt/hash_diff.cairo
Closes #1429
A test failure occurred, particularly noticeable with the
`test_data/22188102.json` fixture, during the execution of the EELS `apply_body`
function within the Python `load_teardown_input` utility
(`cairo/utils/fixture_loader.py`). The issue stemmed from a mismatch between
Keth's internal `State` representation and the format expected by EELS:
1.  Keth's ZKPI loading and internal Python `State` object use `None` to
represent accounts or storage slots that are absent or empty after being
touched in a transaction - the reason being that any key accessed during the
Cairo execution **must** appear in the python object.
2.  The EELS `apply_body` function expects such absent entries to be entirely
missing from the state trie data structures, not represented as `None`. It
also …
> fix: load state compatible with EELS to chunk tx processing

- Cargo.lock
- crates/cairo-addons/Cargo.toml
- crates/cairo-addons/src/lib.rs
- crates/cairo-addons/src/stwo_bindings.rs
- crates/cairo-addons/src/vm/runner.rs
- dictionary.txt
- python/cairo-addons/pyproject.toml
Adds a feature flag that enables profiling memory usage using `dhat`.
> dev: add rust heap profiling with `dhat`

- cairo/tests/ef_tests/helpers/__init__.py
uses the develop fixture instead of stable to get prague-specific tests.
> dev: update ef-tests

- .github/workflows/pull_request.yml
- cairo/ethereum/prague/keth/aggregator.cairo
- cairo/ethereum/prague/keth/main.cairo
- cairo/ethereum/prague/keth/mpt_diff.cairo
- cairo/ethereum/prague/keth/mpt_diff_main.cairo
- cairo/ethereum/prague/keth/teardown.cairo
- cairo/scripts/compile_cairo.py
- cairo/scripts/keth.py
- cairo/scripts/test_keth_cli.py
- cairo/tests/ethereum/prague/keth/test_e2e.cairo
- cairo/tests/ethereum/prague/keth/test_e2e.py
- cairo/tests/ethereum/prague/keth/test_mpt_diff.cairo
- cairo/tests/ethereum/prague/keth/test_mpt_diff.py
- cairo/utils/fixture_loader.py
- python/cairo-addons/src/cairo_addons/hints/main.py
- python/mpt/src/mpt/hash_diff.cairo
- python/mpt/src/mpt/trie_diff.cairo
- python/mpt/src/mpt/trie_diff.py
- python/mpt/tests/src/mpt/test_hash_diff.py
- python/mpt/tests/src/mpt/test_trie_diff.cairo
- python/mpt/tests/src/mpt/test_trie_diff.py
This PR completes the integration of MPT diff processing into Keth's applicative recursion pipeline, enabling efficient verification of
large Ethereum blocks with thousands of MPT nodes.
- Added MPT_DIFF to the Step enum, enabling MPT diff trace generation and proving
- MPT diff processes state changes in 16 parallel chunks (branches 0-15)
- --branch-index: Specifies which MPT branch to process (0-15) for trace and e2e commands
- Example: uv run keth trace -b 22615247 -s mpt_diff --branch-index 0
- generate-ar-inputs now generates 16 additional MPT diff traces automatically
- Total traces for a block: init + body chunks + teardown + 16 mpt_diff + aggregator
- Successfully tested with block 22615247 generating 20 total traces
1. load_mpt_diff_input() in fixture_loader.py:
- Loads teardown …
> feat: split MPT diff traversal
